from __future__ import annotations

import json
import os
import subprocess
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from cavra.runtime import ActionDecision, RuntimeGuard

GO_BACKEND_DISABLED = "disabled"
GO_BACKEND_SHADOW = "shadow"
GO_BACKEND_ENFORCE = "enforce"
GO_BACKEND_PROMOTED = "promoted"
GO_BACKEND_MODES = {
    GO_BACKEND_DISABLED,
    GO_BACKEND_SHADOW,
    GO_BACKEND_ENFORCE,
    GO_BACKEND_PROMOTED,
}


@dataclass(frozen=True)
class GoBackendConfig:
    mode: str = GO_BACKEND_DISABLED
    runtime_path: str = ""
    policy_path: str = ""
    registry_path: str = ""
    package_dir: str = ""
    endpoint_deployment_path: str = ""
    ci_runner_bundles_path: str = ""
    channel_manifest_path: str = ""
    updater_policy_path: str = ""
    promotion_evidence_path: str = ""
    rollback_plan_path: str = ""
    rollback_rehearsal_path: str = ""
    rollback_drill_history_path: str = ""
    rollback_drill_max_age_days: float = 90.0
    timeout_seconds: float = 5.0

    def __post_init__(self) -> None:
        object.__setattr__(self, "mode", _normalized_mode(self.mode))

    @property
    def enabled(self) -> bool:
        return self.mode in {GO_BACKEND_SHADOW, GO_BACKEND_ENFORCE, GO_BACKEND_PROMOTED}


def go_backend_config_from_env() -> GoBackendConfig:
    return GoBackendConfig(
        mode=_normalized_mode(os.environ.get("CAVRA_GO_BACKEND_MODE", GO_BACKEND_DISABLED)),
        runtime_path=os.environ.get("CAVRA_GO_RUNTIME_PATH", ""),
        policy_path=os.environ.get("CAVRA_GO_RUNTIME_POLICY", ""),
        registry_path=os.environ.get("CAVRA_GO_RUNTIME_REGISTRY", ""),
        package_dir=os.environ.get("CAVRA_GO_RUNTIME_PACKAGE_DIR", ""),
        endpoint_deployment_path=os.environ.get("CAVRA_GO_ENDPOINT_DEPLOYMENT_MANIFEST", ""),
        ci_runner_bundles_path=os.environ.get("CAVRA_GO_CI_RUNNER_BUNDLES", ""),
        channel_manifest_path=os.environ.get("CAVRA_GO_WORKSTATION_CHANNELS", ""),
        updater_policy_path=os.environ.get("CAVRA_GO_WORKSTATION_UPDATER_POLICY", ""),
        promotion_evidence_path=os.environ.get("CAVRA_GO_PROMOTION_EVIDENCE", ""),
        rollback_plan_path=os.environ.get("CAVRA_GO_ROLLBACK_PLAN", ""),
        rollback_rehearsal_path=os.environ.get("CAVRA_GO_ROLLBACK_REHEARSAL_EVIDENCE", ""),
        rollback_drill_history_path=os.environ.get("CAVRA_GO_ROLLBACK_DRILL_HISTORY", ""),
        rollback_drill_max_age_days=_float_env("CAVRA_GO_ROLLBACK_DRILL_MAX_AGE_DAYS", 90.0),
        timeout_seconds=_float_env("CAVRA_GO_RUNTIME_TIMEOUT_SECONDS", 5.0),
    )


def go_backend_readiness_report(config: GoBackendConfig | None = None) -> dict[str, Any]:
    config = config or go_backend_config_from_env()
    runtime_exists = bool(config.runtime_path) and Path(config.runtime_path).exists()
    policy_exists = bool(config.policy_path) and Path(config.policy_path).exists()
    registry_exists = not config.registry_path or Path(config.registry_path).exists()
    checks = [
        _check(
            "go_backend_opt_in",
            config.enabled,
            "Go backend is explicitly enabled only when CAVRA_GO_BACKEND_MODE is shadow, enforce, or promoted.",
        ),
        _check(
            "go_runtime_binary",
            runtime_exists,
            "CAVRA_GO_RUNTIME_PATH points to a local cavra-runtime binary.",
            path=config.runtime_path,
        ),
        _check(
            "go_runtime_policy",
            policy_exists,
            "CAVRA_GO_RUNTIME_POLICY points to compiled policy JSON generated by cavra policy compile.",
            path=config.policy_path,
        ),
        _check(
            "go_runtime_registry",
            registry_exists,
            "Optional CAVRA_GO_RUNTIME_REGISTRY path is present when configured.",
            path=config.registry_path,
        ),
        _check(
            "python_fallback",
            True,
            "Python remains authoritative and is used when Go errors, times out, or diverges.",
        ),
        _check(
            "parity_gate",
            True,
            "Go enforcement is accepted only when decision, rule_id, and severity match Python.",
        ),
    ]
    if config.mode == GO_BACKEND_DISABLED:
        status = "disabled"
    elif all(item["status"] == "pass" for item in checks):
        status = "ready"
    else:
        status = "needs_attention"
    return {
        "schema_version": "cavra.go-backend-pilot.readiness.v1",
        "mode": config.mode,
        "status": status,
        "runtime_path": config.runtime_path,
        "policy_path": config.policy_path,
        "registry_path": config.registry_path,
        "timeout_seconds": config.timeout_seconds,
        "checks": checks,
        "operator_notes": [
            "Leave CAVRA_GO_BACKEND_MODE=disabled unless the environment has current parity evidence.",
            "Use shadow mode first; enforce mode still falls back to Python on mismatch or runtime failure.",
            "Use promoted mode only after runtime readiness, deployment readiness, and audited parity evidence pass.",
            "Attach this readiness report to deployment evidence before piloting Go in CI or workstation paths.",
        ],
    }


def go_deployment_readiness_report(config: GoBackendConfig | None = None) -> dict[str, Any]:
    config = config or go_backend_config_from_env()
    package_dir = Path(config.package_dir) if config.package_dir else None
    paths = _deployment_metadata_paths(config, package_dir)
    configured = bool(package_dir or any(path is not None for path in paths.values()))
    checks = [
        _check(
            "go_deployment_metadata_configured",
            configured or not config.enabled,
            "Go deployment metadata is configured before enabling CI runner or workstation rollout paths.",
        ),
        _check(
            "go_release_package_dir",
            not package_dir or package_dir.exists(),
            "Optional CAVRA_GO_RUNTIME_PACKAGE_DIR exists when configured.",
            path=str(package_dir) if package_dir else "",
        ),
    ]
    endpoint = _read_json_check(paths["endpoint_deployment"])
    ci_runner = _read_json_check(paths["ci_runner_bundles"])
    channels = _read_json_check(paths["channel_manifest"])
    updater = _read_json_check(paths["updater_policy"])
    ci_summary = _ci_runner_summary(ci_runner.payload, endpoint.payload)
    workstation_summary = _workstation_summary(channels.payload, updater.payload)
    checks.extend(
        [
            _check(
                "go_endpoint_deployment_manifest",
                endpoint.valid,
                endpoint.message or "Endpoint deployment manifest is present and declares deployment targets.",
                path=_display_path(paths["endpoint_deployment"]),
            ),
            _check(
                "go_ci_runner_bundles",
                ci_runner.valid and ci_summary["valid"],
                ci_summary["message"],
                path=_display_path(paths["ci_runner_bundles"]),
                targets=ci_summary["targets"],
            ),
            _check(
                "go_workstation_channels",
                channels.valid and workstation_summary["channels_valid"],
                workstation_summary["channels_message"],
                path=_display_path(paths["channel_manifest"]),
                channels=workstation_summary["channels"],
                targets=workstation_summary["workstation_targets"],
            ),
            _check(
                "go_workstation_updater_policy",
                updater.valid and workstation_summary["updater_valid"],
                workstation_summary["updater_message"],
                path=_display_path(paths["updater_policy"]),
            ),
        ]
    )
    if not configured:
        status = "needs_attention" if config.enabled else "not_configured"
    elif all(item["status"] == "pass" for item in checks):
        status = "ready"
    else:
        status = "needs_attention"
    return {
        "schema_version": "cavra.go-backend-pilot.deployment-readiness.v1",
        "mode": config.mode,
        "status": status,
        "package_dir": str(package_dir) if package_dir else "",
        "metadata_paths": {name: _display_path(path) for name, path in paths.items()},
        "checks": checks,
        "ci_runner_targets": ci_summary["targets"],
        "workstation_targets": workstation_summary["workstation_targets"],
        "channels": workstation_summary["channels"],
        "operator_notes": [
            "Use a verified Go runtime release package before enabling CI runner or workstation rollout paths.",
            "CI runner bundles must reference signed runtime binaries and publish daemon evidence outputs.",
            "Workstation channel manifests and updater policy must require approval and disable automatic updates by default.",
        ],
    }


def go_promotion_readiness_report(config: GoBackendConfig | None = None) -> dict[str, Any]:
    config = config or go_backend_config_from_env()
    backend = go_backend_readiness_report(config)
    deployment = go_deployment_readiness_report(config)
    evidence = _promotion_evidence_summary(config.promotion_evidence_path)
    requested = config.mode == GO_BACKEND_PROMOTED or bool(config.promotion_evidence_path)
    checks = [
        _check(
            "go_promotion_requested",
            requested,
            "Promoted Go backend mode is requested with CAVRA_GO_BACKEND_MODE=promoted or promotion evidence.",
            mode=config.mode,
        ),
        _check(
            "go_runtime_ready",
            backend["status"] == "ready",
            "Go runtime readiness must pass before promotion.",
            go_backend_status=backend["status"],
        ),
        _check(
            "go_deployment_ready",
            deployment["status"] == "ready",
            "CI runner and workstation deployment readiness must pass before promotion.",
            go_deployment_status=deployment["status"],
        ),
        _check(
            "go_parity_evidence",
            evidence["valid"],
            evidence["message"],
            path=config.promotion_evidence_path,
            evidence_schema=evidence["schema_version"],
        ),
        _check(
            "go_promotion_approval",
            evidence["approved"],
            evidence["approval_message"],
            approval_id=evidence["approval_id"],
        ),
    ]
    if not requested:
        status = "not_requested"
    elif all(item["status"] == "pass" for item in checks):
        status = "ready"
    else:
        status = "needs_attention"
    return {
        "schema_version": "cavra.go-backend-pilot.promotion-readiness.v1",
        "mode": config.mode,
        "status": status,
        "promotion_evidence_path": config.promotion_evidence_path,
        "checks": checks,
        "backend_status": backend["status"],
        "deployment_status": deployment["status"],
        "evidence": evidence,
        "operator_notes": [
            "Promoted mode is an optional backend path, not the default CAVRA runtime.",
            "Keep shadow and enforce pilot evidence attached until promoted mode has current audit approval.",
            "Unset CAVRA_GO_BACKEND_MODE or set disabled to return all decisions to the Python backend.",
        ],
    }


def go_rollback_readiness_report(config: GoBackendConfig | None = None) -> dict[str, Any]:
    config = config or go_backend_config_from_env()
    rollback = _rollback_plan_summary(config.rollback_plan_path)
    requested = config.mode == GO_BACKEND_PROMOTED or bool(config.rollback_plan_path)
    checks = [
        _check(
            "go_rollback_requested",
            requested,
            "Rollback controls are required when CAVRA_GO_BACKEND_MODE=promoted or a rollback plan is configured.",
            mode=config.mode,
        ),
        _check(
            "python_fallback_available",
            True,
            "Python fallback remains available and can be restored by setting CAVRA_GO_BACKEND_MODE=disabled.",
        ),
        _check(
            "go_rollback_plan",
            rollback["valid"],
            rollback["message"],
            path=config.rollback_plan_path,
            rollback_schema=rollback["schema_version"],
        ),
        _check(
            "go_rollback_approval",
            rollback["approved"],
            rollback["approval_message"],
            approval_id=rollback["approval_id"],
        ),
        _check(
            "go_rollback_disable_path",
            rollback["target_mode"] == GO_BACKEND_DISABLED,
            rollback["target_mode_message"],
            target_mode=rollback["target_mode"],
        ),
        _check(
            "go_rollback_controls",
            rollback["controls_valid"],
            rollback["controls_message"],
            missing_controls=rollback["missing_controls"],
        ),
    ]
    if not requested:
        status = "not_requested"
    elif all(item["status"] == "pass" for item in checks):
        status = "ready"
    else:
        status = "needs_attention"
    return {
        "schema_version": "cavra.go-backend-pilot.rollback-readiness.v1",
        "mode": config.mode,
        "status": status,
        "rollback_plan_path": config.rollback_plan_path,
        "checks": checks,
        "rollback": rollback,
        "operator_notes": [
            "Promoted Go backend pilots must have a documented path back to Python-only mode.",
            "The rollback plan is public-safe metadata; do not include private keys, secrets, or customer data.",
            "Set CAVRA_GO_BACKEND_MODE=disabled to force Python backend selection during rollback.",
        ],
    }


def go_rollback_rehearsal_report(config: GoBackendConfig | None = None) -> dict[str, Any]:
    config = config or go_backend_config_from_env()
    rollback = _rollback_plan_summary(config.rollback_plan_path)
    rehearsal = _rollback_rehearsal_summary(config.rollback_rehearsal_path, rollback)
    requested = config.mode == GO_BACKEND_PROMOTED or bool(config.rollback_rehearsal_path)
    checks = [
        _check(
            "go_rollback_rehearsal_requested",
            requested,
            "Rollback rehearsal evidence is required when CAVRA_GO_BACKEND_MODE=promoted or rehearsal evidence is configured.",
            mode=config.mode,
        ),
        _check(
            "go_rollback_rehearsal_evidence",
            rehearsal["valid"],
            rehearsal["message"],
            path=config.rollback_rehearsal_path,
            rehearsal_schema=rehearsal["schema_version"],
        ),
        _check(
            "go_rollback_rehearsal_simulated",
            rehearsal["simulated"] is True,
            rehearsal["simulation_message"],
        ),
        _check(
            "go_rollback_rehearsal_fallback_verified",
            rehearsal["fallback_verified"] is True,
            rehearsal["fallback_message"],
        ),
        _check(
            "go_rollback_rehearsal_recovery_sla",
            rehearsal["recovery_sla_met"],
            rehearsal["recovery_message"],
            recovery_minutes=rehearsal["recovery_minutes"],
            max_recovery_minutes=rehearsal["max_recovery_minutes"],
        ),
        _check(
            "go_rollback_rehearsal_evidence_refs",
            bool(rehearsal["evidence_refs"]),
            rehearsal["evidence_message"],
            evidence_refs=rehearsal["evidence_refs"],
        ),
    ]
    if not requested:
        status = "not_requested"
    elif all(item["status"] == "pass" for item in checks):
        status = "ready"
    else:
        status = "needs_attention"
    return {
        "schema_version": "cavra.go-backend-pilot.rollback-rehearsal.v1",
        "mode": config.mode,
        "status": status,
        "rollback_rehearsal_path": config.rollback_rehearsal_path,
        "checks": checks,
        "rehearsal": rehearsal,
        "operator_notes": [
            "Run rollback rehearsals outside the console and attach public-safe evidence metadata here.",
            "Rehearsals must prove that promoted mode can return to Python-only mode within the approved recovery target.",
            "Do not include secrets, customer data, or private endpoint scripts in rehearsal evidence.",
        ],
    }


def go_rollback_drill_history_report(config: GoBackendConfig | None = None) -> dict[str, Any]:
    config = config or go_backend_config_from_env()
    history = _rollback_drill_history_summary(
        config.rollback_drill_history_path,
        max_age_days=config.rollback_drill_max_age_days,
    )
    requested = config.mode == GO_BACKEND_PROMOTED or bool(config.rollback_drill_history_path)
    checks = [
        _check(
            "go_rollback_drill_history_requested",
            requested,
            "Rollback drill history is required when CAVRA_GO_BACKEND_MODE=promoted or drill history is configured.",
            mode=config.mode,
        ),
        _check(
            "go_rollback_drill_history_file",
            history["valid"],
            history["message"],
            path=config.rollback_drill_history_path,
            history_schema=history["schema_version"],
        ),
        _check(
            "go_rollback_drill_latest_passed",
            history["latest_status"] == "pass",
            history["latest_status_message"],
            latest_drill_id=history["latest_drill_id"],
        ),
        _check(
            "go_rollback_drill_disabled_target",
            history["latest_target_mode"] == GO_BACKEND_DISABLED,
            history["target_mode_message"],
            target_mode=history["latest_target_mode"],
        ),
        _check(
            "go_rollback_drill_fallback_verified",
            history["fallback_verified"] is True,
            history["fallback_message"],
        ),
        _check(
            "go_rollback_drill_recovery_sla",
            history["recovery_sla_met"],
            history["recovery_message"],
            recovery_minutes=history["recovery_minutes"],
            max_recovery_minutes=history["max_recovery_minutes"],
        ),
        _check(
            "go_rollback_drill_freshness",
            history["fresh"],
            history["freshness_message"],
            max_age_days=config.rollback_drill_max_age_days,
            age_days=history["age_days"],
        ),
    ]
    if not requested:
        status = "not_requested"
    elif all(item["status"] == "pass" for item in checks):
        status = "ready"
    else:
        status = "needs_attention"
    return {
        "schema_version": "cavra.go-backend-pilot.rollback-drill-history.v1",
        "mode": config.mode,
        "status": status,
        "rollback_drill_history_path": config.rollback_drill_history_path,
        "rollback_drill_max_age_days": config.rollback_drill_max_age_days,
        "checks": checks,
        "history": history,
        "operator_notes": [
            "Drill history is public-safe metadata that proves promoted environments can return to Python-only mode.",
            "Record drills from operational runbooks; do not execute rollback from the browser.",
            "Keep hostnames, private endpoint scripts, secrets, and customer details out of public drill history.",
        ],
    }


def evaluate_with_go_pilot(
    request: dict[str, Any],
    *,
    config: GoBackendConfig | None = None,
) -> dict[str, Any]:
    config = config or go_backend_config_from_env()
    python_decision = _python_decision(request)
    result: dict[str, Any] = {
        "schema_version": "cavra.go-backend-pilot.evaluation.v1",
        "backend_mode": config.mode,
        "selected_backend": "python",
        "fallback_used": False,
        "fallback_reason": "",
        "parity_match": None,
        "python_decision": python_decision.to_dict(),
        "go_decision": None,
        "effective_decision": python_decision.to_dict(),
    }
    if not config.enabled:
        result["fallback_reason"] = "go backend pilot is disabled"
        return result
    readiness = go_backend_readiness_report(config)
    blocking = [item for item in readiness["checks"] if item["status"] != "pass" and item["id"] != "go_backend_opt_in"]
    if blocking:
        result["fallback_used"] = True
        result["fallback_reason"] = "go backend readiness check failed"
        result["readiness"] = readiness
        return result
    if config.mode == GO_BACKEND_PROMOTED:
        promotion = go_promotion_readiness_report(config)
        if promotion["status"] != "ready":
            result["fallback_used"] = True
            result["fallback_reason"] = "go backend promotion readiness check failed"
            result["readiness"] = readiness
            result["promotion_readiness"] = promotion
            return result
        rollback = go_rollback_readiness_report(config)
        if rollback["status"] != "ready":
            result["fallback_used"] = True
            result["fallback_reason"] = "go backend rollback readiness check failed"
            result["readiness"] = readiness
            result["promotion_readiness"] = promotion
            result["rollback_readiness"] = rollback
            return result
        rehearsal = go_rollback_rehearsal_report(config)
        if rehearsal["status"] != "ready":
            result["fallback_used"] = True
            result["fallback_reason"] = "go backend rollback rehearsal check failed"
            result["readiness"] = readiness
            result["promotion_readiness"] = promotion
            result["rollback_readiness"] = rollback
            result["rollback_rehearsal"] = rehearsal
            return result
        drills = go_rollback_drill_history_report(config)
        if drills["status"] != "ready":
            result["fallback_used"] = True
            result["fallback_reason"] = "go backend rollback drill history check failed"
            result["readiness"] = readiness
            result["promotion_readiness"] = promotion
            result["rollback_readiness"] = rollback
            result["rollback_rehearsal"] = rehearsal
            result["rollback_drill_history"] = drills
            return result
    try:
        go_decision = _run_go_runtime(request, config)
    except (subprocess.SubprocessError, OSError, json.JSONDecodeError) as exc:
        result["fallback_used"] = True
        result["fallback_reason"] = f"go runtime failed: {exc}"
        result["readiness"] = readiness
        return result
    result["go_decision"] = go_decision
    parity_match = _decisions_match(python_decision.to_dict(), go_decision)
    result["parity_match"] = parity_match
    if not parity_match:
        result["fallback_used"] = True
        result["fallback_reason"] = "go decision diverged from Python parity gate"
        return result
    if config.mode in {GO_BACKEND_ENFORCE, GO_BACKEND_PROMOTED}:
        result["selected_backend"] = "go"
        result["effective_decision"] = go_decision
    return result


def _python_decision(request: dict[str, Any]) -> ActionDecision:
    guard = RuntimeGuard(
        policy_pack=str(request.get("policy_pack") or "cavra-ai-agent-baseline"),
        session_id=str(request.get("session_id", "local")),
        agent_id=str(request.get("agent_id", "unknown-agent")),
        actor=str(request.get("actor", "ai-agent")),
    )
    action_type = str(request.get("action_type", ""))
    target = str(request.get("target", ""))
    if action_type == "read_file":
        return guard.evaluate_file_access(Path(target), "read")
    if action_type == "write_file":
        return guard.evaluate_file_access(Path(target), "write")
    if action_type == "execute_command":
        return guard.evaluate_command(target)
    if action_type == "git_operation":
        return guard.evaluate_git_action(str(request.get("operation", "push")), target)
    if action_type == "mcp_tool_call":
        return guard.evaluate_mcp_tool_call(
            str(request.get("server", target)),
            str(request.get("tool", "unknown")),
            str(request.get("capability", "")) or None,
        )
    if action_type == "release_governance_record":
        record = request.get("record") or request.get("release_governance")
        return guard.evaluate_release_governance_record(
            record if isinstance(record, dict) else {},
            target=target or None,
            requested_operation=str(request.get("operation", request.get("requested_operation", "verify"))),
        )
    return ActionDecision(
        decision="require_approval",
        reason="Unknown action type; review required.",
        session_id=str(request.get("session_id", "local")),
        agent_id=str(request.get("agent_id", "unknown-agent")),
        actor=str(request.get("actor", "ai-agent")),
        action_type=action_type or "unknown",
        target=target,
        requested_operation=str(request.get("operation", "")),
        policy_pack=str(request.get("policy_pack") or "cavra-ai-agent-baseline"),
        policy_id=str(request.get("policy_pack") or "cavra-ai-agent-baseline"),
        rule_id="runtime.default.require_approval",
        severity="medium",
        approver_group="Repository Owners",
    )


def _run_go_runtime(request: dict[str, Any], config: GoBackendConfig) -> dict[str, Any]:
    command = [config.runtime_path, "--policy", config.policy_path]
    if config.registry_path:
        command.extend(["--registry", config.registry_path])
    completed = subprocess.run(
        command,
        input=json.dumps(request),
        text=True,
        capture_output=True,
        timeout=config.timeout_seconds,
        check=True,
    )
    return json.loads(completed.stdout)


def _decisions_match(python_decision: dict[str, Any], go_decision: dict[str, Any]) -> bool:
    return all(
        python_decision.get(field) == go_decision.get(field)
        for field in ("decision", "rule_id", "severity")
    )


def _normalized_mode(value: str) -> str:
    mode = value.strip().lower() or GO_BACKEND_DISABLED
    return mode if mode in GO_BACKEND_MODES else GO_BACKEND_DISABLED


def _float_env(name: str, default: float) -> float:
    try:
        return float(os.environ.get(name, default))
    except (TypeError, ValueError):
        return default


def _check(check_id: str, passed: bool, message: str, **extra: Any) -> dict[str, Any]:
    return {"id": check_id, "status": "pass" if passed else "warn", "message": message, **extra}


def _deployment_metadata_paths(config: GoBackendConfig, package_dir: Path | None) -> dict[str, Path | None]:
    return {
        "endpoint_deployment": _configured_path(
            config.endpoint_deployment_path,
            package_dir,
            "cavra-runtime.endpoint-deployment.json",
        ),
        "ci_runner_bundles": _configured_path(
            config.ci_runner_bundles_path,
            package_dir,
            "cavra-runtime.ci-runner-bundles.json",
        ),
        "channel_manifest": _configured_path(
            config.channel_manifest_path,
            package_dir,
            "cavra-runtime.channels.json",
        ),
        "updater_policy": _configured_path(
            config.updater_policy_path,
            package_dir,
            "cavra-runtime.updater-policy.json",
        ),
    }


def _configured_path(value: str, package_dir: Path | None, default_name: str) -> Path | None:
    if value:
        return Path(value)
    if package_dir:
        return package_dir / default_name
    return None


def _display_path(path: Path | None) -> str:
    return str(path) if path else ""


@dataclass(frozen=True)
class _JsonCheck:
    valid: bool
    message: str
    payload: dict[str, Any]


def _read_json_check(path: Path | None) -> _JsonCheck:
    if path is None:
        return _JsonCheck(False, "metadata path is not configured", {})
    if not path.exists() or not path.is_file():
        return _JsonCheck(False, "metadata file is missing", {})
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        return _JsonCheck(False, f"metadata JSON is invalid: {exc}", {})
    if not isinstance(payload, dict):
        return _JsonCheck(False, "metadata JSON must be an object", {})
    return _JsonCheck(True, "metadata file is present and parseable", payload)


def _promotion_evidence_summary(path_value: str) -> dict[str, Any]:
    check = _read_json_check(Path(path_value) if path_value else None)
    if not check.valid:
        return {
            "valid": False,
            "approved": False,
            "schema_version": "",
            "approval_id": "",
            "message": check.message,
            "approval_message": "promotion evidence is missing or invalid",
            "evidence_refs": [],
        }
    payload = check.payload
    schema = str(payload.get("schema_version", ""))
    parity = payload.get("parity") if isinstance(payload.get("parity"), dict) else {}
    deployment = payload.get("deployment") if isinstance(payload.get("deployment"), dict) else {}
    approval = payload.get("approval") if isinstance(payload.get("approval"), dict) else {}
    parity_status = str(payload.get("parity_status") or parity.get("status") or "")
    deployment_status = str(payload.get("deployment_status") or deployment.get("status") or "")
    approved = payload.get("approved") is True or approval.get("status") == "approved"
    approval_id = str(payload.get("approval_id") or approval.get("approval_id") or "")
    evidence_refs = payload.get("evidence_refs", [])
    refs_valid = isinstance(evidence_refs, list) and all(isinstance(item, str) for item in evidence_refs)
    valid = (
        schema == "cavra.go-backend-promotion-evidence.v1"
        and parity_status == "pass"
        and deployment_status == "ready"
        and refs_valid
    )
    messages = []
    if schema != "cavra.go-backend-promotion-evidence.v1":
        messages.append("promotion evidence has an invalid schema_version")
    if parity_status != "pass":
        messages.append("promotion evidence must record parity_status=pass")
    if deployment_status != "ready":
        messages.append("promotion evidence must record deployment_status=ready")
    if not refs_valid:
        messages.append("promotion evidence_refs must be a list of strings")
    return {
        "valid": valid,
        "approved": approved,
        "schema_version": schema,
        "approval_id": approval_id,
        "message": "; ".join(messages) if messages else "Promotion evidence records audited parity and deployment readiness.",
        "approval_message": "Promotion approval is recorded." if approved else "promotion evidence must be approved",
        "evidence_refs": evidence_refs if refs_valid else [],
        "parity_status": parity_status,
        "deployment_status": deployment_status,
    }


def _rollback_plan_summary(path_value: str) -> dict[str, Any]:
    check = _read_json_check(Path(path_value) if path_value else None)
    required_controls = {
        "python-fallback-available",
        "promoted-mode-disable-tested",
        "rollback-approval-recorded",
        "operator-runbook-linked",
        "evidence-capture-enabled",
    }
    if not check.valid:
        return {
            "valid": False,
            "approved": False,
            "controls_valid": False,
            "schema_version": "",
            "approval_id": "",
            "target_mode": "",
            "message": check.message,
            "approval_message": "rollback plan is missing or invalid",
            "target_mode_message": "rollback plan must set target_mode=disabled",
            "controls_message": "rollback plan controls are missing",
            "missing_controls": sorted(required_controls),
            "evidence_refs": [],
            "rollback_steps": [],
            "max_recovery_minutes": None,
        }
    payload = check.payload
    schema = str(payload.get("schema_version", ""))
    approval = payload.get("approval") if isinstance(payload.get("approval"), dict) else {}
    approved = payload.get("approved") is True or approval.get("status") == "approved"
    approval_id = str(payload.get("approval_id") or approval.get("approval_id") or "")
    target_mode = str(payload.get("target_mode", ""))
    controls = {str(item) for item in payload.get("controls", []) if isinstance(item, str)}
    missing_controls = sorted(required_controls - controls)
    rollback_steps = payload.get("rollback_steps", [])
    evidence_refs = payload.get("evidence_refs", [])
    steps_valid = isinstance(rollback_steps, list) and all(isinstance(item, str) for item in rollback_steps)
    refs_valid = isinstance(evidence_refs, list) and all(isinstance(item, str) for item in evidence_refs)
    status = str(payload.get("status", ""))
    max_recovery = payload.get("max_recovery_minutes")
    max_recovery_valid = isinstance(max_recovery, (int, float)) and not isinstance(max_recovery, bool) and max_recovery > 0
    valid = (
        schema == "cavra.go-backend-rollback-plan.v1"
        and status == "ready"
        and target_mode == GO_BACKEND_DISABLED
        and not missing_controls
        and steps_valid
        and bool(rollback_steps)
        and refs_valid
        and max_recovery_valid
    )
    messages = []
    if schema != "cavra.go-backend-rollback-plan.v1":
        messages.append("rollback plan has an invalid schema_version")
    if status != "ready":
        messages.append("rollback plan must record status=ready")
    if not steps_valid or not rollback_steps:
        messages.append("rollback plan must include rollback_steps as a non-empty list of strings")
    if not refs_valid:
        messages.append("rollback evidence_refs must be a list of strings")
    if not max_recovery_valid:
        messages.append("rollback plan must include positive max_recovery_minutes")
    return {
        "valid": valid,
        "approved": approved,
        "controls_valid": not missing_controls,
        "schema_version": schema,
        "approval_id": approval_id,
        "target_mode": target_mode,
        "message": "; ".join(messages) if messages else "Rollback plan is ready for promoted Go backend pilots.",
        "approval_message": "Rollback approval is recorded." if approved else "rollback plan must be approved",
        "target_mode_message": "Rollback returns CAVRA to Python-only mode." if target_mode == GO_BACKEND_DISABLED else "rollback plan must set target_mode=disabled",
        "controls_message": "Rollback controls are complete." if not missing_controls else f"rollback plan is missing controls: {', '.join(missing_controls)}",
        "missing_controls": missing_controls,
        "evidence_refs": evidence_refs if refs_valid else [],
        "rollback_steps": rollback_steps if steps_valid else [],
        "max_recovery_minutes": max_recovery if max_recovery_valid else None,
    }


def _rollback_rehearsal_summary(path_value: str, rollback: dict[str, Any]) -> dict[str, Any]:
    check = _read_json_check(Path(path_value) if path_value else None)
    if not check.valid:
        return {
            "valid": False,
            "schema_version": "",
            "status": "",
            "plan_approval_id": "",
            "simulated": False,
            "fallback_verified": False,
            "recovery_sla_met": False,
            "recovery_minutes": None,
            "max_recovery_minutes": rollback.get("max_recovery_minutes"),
            "evidence_refs": [],
            "runbook_ref": "",
            "message": check.message,
            "simulation_message": "rollback rehearsal evidence is missing or invalid",
            "fallback_message": "rollback rehearsal must verify Python fallback restoration",
            "recovery_message": "rollback rehearsal must record recovery_minutes within max_recovery_minutes",
            "evidence_message": "rollback rehearsal must include evidence_refs",
        }
    payload = check.payload
    schema = str(payload.get("schema_version", ""))
    status = str(payload.get("status", ""))
    plan_approval_id = str(payload.get("plan_approval_id") or payload.get("approval_id") or "")
    simulated = payload.get("simulated") is True
    fallback_verified = payload.get("fallback_verified") is True
    recovery_minutes = payload.get("recovery_minutes")
    rehearsal_max_recovery = payload.get("max_recovery_minutes")
    plan_max_recovery = rollback.get("max_recovery_minutes")
    max_recovery = rehearsal_max_recovery if _positive_number(rehearsal_max_recovery) else plan_max_recovery
    evidence_refs = payload.get("evidence_refs", [])
    refs_valid = isinstance(evidence_refs, list) and all(isinstance(item, str) for item in evidence_refs)
    runbook_ref = str(payload.get("runbook_ref", ""))
    recovery_valid = _positive_number(recovery_minutes)
    max_recovery_valid = _positive_number(max_recovery)
    recovery_sla_met = bool(recovery_valid and max_recovery_valid and recovery_minutes <= max_recovery)
    rollback_approval_id = str(rollback.get("approval_id", ""))
    approval_matches = not rollback_approval_id or plan_approval_id == rollback_approval_id
    valid = (
        schema == "cavra.go-backend-rollback-rehearsal.v1"
        and status == "pass"
        and simulated
        and fallback_verified
        and recovery_sla_met
        and refs_valid
        and bool(evidence_refs)
        and bool(runbook_ref)
        and approval_matches
    )
    messages = []
    if schema != "cavra.go-backend-rollback-rehearsal.v1":
        messages.append("rollback rehearsal evidence has an invalid schema_version")
    if status != "pass":
        messages.append("rollback rehearsal evidence must record status=pass")
    if not bool(runbook_ref):
        messages.append("rollback rehearsal evidence must include runbook_ref")
    if not refs_valid or not evidence_refs:
        messages.append("rollback rehearsal evidence_refs must be a non-empty list of strings")
    if not approval_matches:
        messages.append("rollback rehearsal plan_approval_id must match the rollback plan approval_id")
    return {
        "valid": valid,
        "schema_version": schema,
        "status": status,
        "plan_approval_id": plan_approval_id,
        "simulated": simulated,
        "fallback_verified": fallback_verified,
        "recovery_sla_met": recovery_sla_met,
        "recovery_minutes": recovery_minutes if recovery_valid else None,
        "max_recovery_minutes": max_recovery if max_recovery_valid else None,
        "evidence_refs": evidence_refs if refs_valid else [],
        "runbook_ref": runbook_ref,
        "message": "; ".join(messages) if messages else "Rollback rehearsal evidence proves Python fallback restoration within the approved recovery target.",
        "simulation_message": "Rollback rehearsal was simulated." if simulated else "rollback rehearsal must be marked simulated=true",
        "fallback_message": "Python fallback restoration was verified." if fallback_verified else "rollback rehearsal must verify Python fallback restoration",
        "recovery_message": "Recovery target was met." if recovery_sla_met else "rollback rehearsal recovery_minutes must be positive and less than or equal to max_recovery_minutes",
        "evidence_message": "Rollback rehearsal evidence references are recorded." if refs_valid and evidence_refs else "rollback rehearsal must include evidence_refs",
    }


def _rollback_drill_history_summary(path_value: str, *, max_age_days: float) -> dict[str, Any]:
    check = _read_json_check(Path(path_value) if path_value else None)
    if not check.valid:
        return _empty_drill_history_summary(check.message)
    payload = check.payload
    schema = str(payload.get("schema_version", ""))
    drills = payload.get("drills", [])
    if schema != "cavra.go-backend-rollback-drill-history.v1" or not isinstance(drills, list) or not drills:
        messages = []
        if schema != "cavra.go-backend-rollback-drill-history.v1":
            messages.append("rollback drill history has an invalid schema_version")
        if not isinstance(drills, list) or not drills:
            messages.append("rollback drill history must include a non-empty drills list")
        return _empty_drill_history_summary("; ".join(messages))
    valid_drills = [item for item in drills if isinstance(item, dict)]
    latest = _latest_drill(valid_drills)
    if latest is None:
        return _empty_drill_history_summary("rollback drill history has no parseable drills")
    executed_at = str(latest.get("executed_at", ""))
    executed = _parse_iso_datetime(executed_at)
    now = datetime.now(timezone.utc)
    age_days = None
    fresh = False
    if executed is not None and _positive_number(max_age_days):
        age_days = round((now - executed).total_seconds() / 86400, 4)
        fresh = age_days <= max_age_days
    status = str(latest.get("status", ""))
    target_mode = str(latest.get("target_mode", ""))
    fallback_verified = latest.get("fallback_verified") is True
    recovery_minutes = latest.get("recovery_minutes")
    max_recovery = latest.get("max_recovery_minutes")
    recovery_valid = _positive_number(recovery_minutes)
    max_recovery_valid = _positive_number(max_recovery)
    recovery_sla_met = bool(recovery_valid and max_recovery_valid and recovery_minutes <= max_recovery)
    evidence_refs = latest.get("evidence_refs", [])
    refs_valid = isinstance(evidence_refs, list) and all(isinstance(item, str) for item in evidence_refs)
    runbook_ref = str(latest.get("runbook_ref", ""))
    valid = (
        status == "pass"
        and target_mode == GO_BACKEND_DISABLED
        and fallback_verified
        and recovery_sla_met
        and fresh
        and refs_valid
        and bool(evidence_refs)
        and bool(runbook_ref)
    )
    messages = []
    if not refs_valid or not evidence_refs:
        messages.append("latest rollback drill must include evidence_refs as a non-empty list of strings")
    if not bool(runbook_ref):
        messages.append("latest rollback drill must include runbook_ref")
    if executed is None:
        messages.append("latest rollback drill must include valid executed_at timestamp")
    return {
        "valid": valid,
        "schema_version": schema,
        "environment": str(payload.get("environment", "")),
        "drill_count": len(valid_drills),
        "latest_drill_id": str(latest.get("drill_id", "")),
        "latest_status": status,
        "latest_target_mode": target_mode,
        "latest_executed_at": executed_at,
        "age_days": age_days,
        "fresh": fresh,
        "fallback_verified": fallback_verified,
        "recovery_sla_met": recovery_sla_met,
        "recovery_minutes": recovery_minutes if recovery_valid else None,
        "max_recovery_minutes": max_recovery if max_recovery_valid else None,
        "runbook_ref": runbook_ref,
        "evidence_refs": evidence_refs if refs_valid else [],
        "message": "; ".join(messages) if messages else "Rollback drill history is parseable and latest drill is evaluated.",
        "latest_status_message": "Latest rollback drill passed." if status == "pass" else "latest rollback drill must record status=pass",
        "target_mode_message": "Latest rollback drill returned to Python-only mode." if target_mode == GO_BACKEND_DISABLED else "latest rollback drill must set target_mode=disabled",
        "fallback_message": "Latest rollback drill verified Python fallback restoration." if fallback_verified else "latest rollback drill must verify Python fallback restoration",
        "recovery_message": "Latest rollback drill met the recovery target." if recovery_sla_met else "latest rollback drill recovery_minutes must be positive and less than or equal to max_recovery_minutes",
        "freshness_message": "Latest rollback drill is within the freshness window." if fresh else "latest rollback drill is missing, invalid, or stale",
    }


def _empty_drill_history_summary(message: str) -> dict[str, Any]:
    return {
        "valid": False,
        "schema_version": "",
        "environment": "",
        "drill_count": 0,
        "latest_drill_id": "",
        "latest_status": "",
        "latest_target_mode": "",
        "latest_executed_at": "",
        "age_days": None,
        "fresh": False,
        "fallback_verified": False,
        "recovery_sla_met": False,
        "recovery_minutes": None,
        "max_recovery_minutes": None,
        "runbook_ref": "",
        "evidence_refs": [],
        "message": message,
        "latest_status_message": "rollback drill history is missing or invalid",
        "target_mode_message": "latest rollback drill must set target_mode=disabled",
        "fallback_message": "latest rollback drill must verify Python fallback restoration",
        "recovery_message": "latest rollback drill recovery_minutes must be positive and less than or equal to max_recovery_minutes",
        "freshness_message": "latest rollback drill is missing, invalid, or stale",
    }


def _latest_drill(drills: list[dict[str, Any]]) -> dict[str, Any] | None:
    dated = []
    for drill in drills:
        executed = _parse_iso_datetime(str(drill.get("executed_at", "")))
        if executed is not None:
            dated.append((executed, drill))
    if dated:
        return max(dated, key=lambda item: item[0])[1]
    return drills[-1] if drills else None


def _parse_iso_datetime(value: str) -> datetime | None:
    if not value:
        return None
    normalized = value.replace("Z", "+00:00")
    try:
        parsed = datetime.fromisoformat(normalized)
    except ValueError:
        return None
    if parsed.tzinfo is None:
        return parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc)


def _positive_number(value: Any) -> bool:
    return isinstance(value, (int, float)) and not isinstance(value, bool) and value > 0


def _ci_runner_summary(ci_payload: dict[str, Any], endpoint_payload: dict[str, Any]) -> dict[str, Any]:
    targets = []
    messages = []
    valid = True
    if ci_payload.get("schema_version") != "cavra.go-runtime.ci-runner-bundles.v1":
        valid = False
        messages.append("CI runner bundle metadata has an invalid schema_version")
    if ci_payload.get("source_metadata") != "cavra-runtime.endpoint-deployment.json":
        valid = False
        messages.append("CI runner bundle metadata must reference cavra-runtime.endpoint-deployment.json")
    controls = {str(item) for item in ci_payload.get("controls", []) if isinstance(item, str)}
    required_controls = {
        "verified-signed-runtime-before-runner-use",
        "runner-authentication-claims-signed",
        "runner-authentication-oidc-verified",
        "daemon-evidence-stream-hmac-signed",
        "evidence-verification-artifact-published",
        "blocking-decision-fails-closed-by-default",
    }
    missing_controls = sorted(required_controls - controls)
    if missing_controls:
        valid = False
        messages.append(f"CI runner bundle metadata is missing controls: {', '.join(missing_controls)}")
    endpoint_targets = {
        str(target.get("id")): target
        for target in endpoint_payload.get("deployment_targets", [])
        if isinstance(target, dict) and target.get("id")
    }
    bundles = ci_payload.get("runner_bundles")
    if not isinstance(bundles, list) or not bundles:
        valid = False
        messages.append("CI runner bundle metadata has no runner_bundles")
    else:
        for bundle in bundles:
            if not isinstance(bundle, dict):
                valid = False
                messages.append("CI runner bundle entry is invalid")
                continue
            target_id = str(bundle.get("deployment_target", ""))
            target = endpoint_targets.get(target_id)
            targets.append(
                {
                    "deployment_target": target_id,
                    "platform": str(bundle.get("platform", "")),
                    "runtime_binary": str(bundle.get("runtime_binary", "")),
                    "surface": str(target.get("surface", "")) if target else "",
                }
            )
            if not target_id or not bundle.get("platform"):
                valid = False
                messages.append("CI runner bundle entry is missing platform or deployment_target")
            if not target or target.get("surface") != "ci-runner":
                valid = False
                messages.append(f"CI runner bundle references an invalid CI runner target: {target_id or 'unknown'}")
            outputs = bundle.get("required_outputs")
            output_text = "\n".join(str(output) for output in outputs) if isinstance(outputs, list) else ""
            if "release-governance-evidence-verification.json" not in output_text:
                valid = False
                messages.append(f"CI runner bundle is missing evidence verification output: {target_id or 'unknown'}")
    return {
        "valid": valid,
        "targets": targets,
        "message": "; ".join(messages) if messages else "CI runner bundles are ready for governed runner rollout.",
    }


def _workstation_summary(channels_payload: dict[str, Any], updater_payload: dict[str, Any]) -> dict[str, Any]:
    channels = []
    workstation_targets = []
    channel_messages = []
    updater_messages = []
    channels_valid = True
    updater_valid = True
    if channels_payload.get("schema_version") != "cavra.go-runtime.channels.v1":
        channels_valid = False
        channel_messages.append("workstation channel manifest has an invalid schema_version")
    if channels_payload.get("source_metadata") != "cavra-runtime.endpoint-deployment.json":
        channels_valid = False
        channel_messages.append("workstation channel manifest must reference cavra-runtime.endpoint-deployment.json")
    for channel in channels_payload.get("channels", []):
        if not isinstance(channel, dict):
            channels_valid = False
            channel_messages.append("workstation channel entry is invalid")
            continue
        channel_name = str(channel.get("channel", ""))
        channels.append(channel_name)
        if channel.get("auto_update") is not False or channel.get("approval_required") is not True:
            channels_valid = False
            channel_messages.append(f"channel {channel_name or 'unknown'} must require approval and disable auto update")
        targets = channel.get("workstation_targets")
        if not isinstance(targets, list) or not targets:
            channels_valid = False
            channel_messages.append(f"channel {channel_name or 'unknown'} has no workstation targets")
            continue
        for target in targets:
            if not isinstance(target, dict):
                channels_valid = False
                channel_messages.append(f"channel {channel_name or 'unknown'} workstation target is invalid")
                continue
            workstation_targets.append(
                {
                    "channel": channel_name,
                    "deployment_target": str(target.get("id", "")),
                    "platform": str(target.get("platform", "")),
                    "management_tool": str(target.get("management_tool", "")),
                    "binary": str(target.get("binary", "")),
                }
            )
            if any(not target.get(field) for field in ("id", "platform", "deployment_channel", "management_tool")):
                channels_valid = False
                channel_messages.append(f"channel {channel_name or 'unknown'} target is missing deployment guidance")
    if not channels:
        channels_valid = False
        channel_messages.append("workstation channel manifest has no channels")
    if updater_payload.get("schema_version") != "cavra.go-runtime.updater-policy.v1":
        updater_valid = False
        updater_messages.append("workstation updater policy has an invalid schema_version")
    if updater_payload.get("source_channel_manifest") != "cavra-runtime.channels.json":
        updater_valid = False
        updater_messages.append("workstation updater policy must reference cavra-runtime.channels.json")
    if updater_payload.get("default_auto_update") is not False:
        updater_valid = False
        updater_messages.append("workstation updater policy must disable default auto update")
    policies = updater_payload.get("policies")
    policy_channels = {str(item.get("channel")) for item in policies if isinstance(item, dict) and item.get("channel")} if isinstance(policies, list) else set()
    if not policy_channels:
        updater_valid = False
        updater_messages.append("workstation updater policy has no channel policies")
    if channels and policy_channels and policy_channels != set(channels):
        updater_valid = False
        updater_messages.append("workstation updater policy channels must match channel manifest channels")
    return {
        "channels_valid": channels_valid,
        "updater_valid": updater_valid,
        "channels": channels,
        "workstation_targets": workstation_targets,
        "channels_message": "; ".join(channel_messages) if channel_messages else "Workstation channels are approval-bound and ready.",
        "updater_message": "; ".join(updater_messages) if updater_messages else "Workstation updater policy is approval-bound and ready.",
    }
