from __future__ import annotations

import json
import os
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from cavra.runtime import ActionDecision, RuntimeGuard

GO_BACKEND_DISABLED = "disabled"
GO_BACKEND_SHADOW = "shadow"
GO_BACKEND_ENFORCE = "enforce"
GO_BACKEND_MODES = {GO_BACKEND_DISABLED, GO_BACKEND_SHADOW, GO_BACKEND_ENFORCE}


@dataclass(frozen=True)
class GoBackendConfig:
    mode: str = GO_BACKEND_DISABLED
    runtime_path: str = ""
    policy_path: str = ""
    registry_path: str = ""
    timeout_seconds: float = 5.0

    def __post_init__(self) -> None:
        object.__setattr__(self, "mode", _normalized_mode(self.mode))

    @property
    def enabled(self) -> bool:
        return self.mode in {GO_BACKEND_SHADOW, GO_BACKEND_ENFORCE}


def go_backend_config_from_env() -> GoBackendConfig:
    return GoBackendConfig(
        mode=_normalized_mode(os.environ.get("CAVRA_GO_BACKEND_MODE", GO_BACKEND_DISABLED)),
        runtime_path=os.environ.get("CAVRA_GO_RUNTIME_PATH", ""),
        policy_path=os.environ.get("CAVRA_GO_RUNTIME_POLICY", ""),
        registry_path=os.environ.get("CAVRA_GO_RUNTIME_REGISTRY", ""),
        timeout_seconds=_float_env("CAVRA_GO_RUNTIME_TIMEOUT_SECONDS", 5.0),
    )


def go_backend_readiness_report(config: GoBackendConfig | None = None) -> dict[str, Any]:
    config = config or go_backend_config_from_env()
    runtime_exists = bool(config.runtime_path) and Path(config.runtime_path).exists()
    policy_exists = bool(config.policy_path) and Path(config.policy_path).exists()
    registry_exists = not config.registry_path or Path(config.registry_path).exists()
    checks = [
        _check(
            "go_backend_opt_in",
            config.enabled,
            "Go backend pilot is explicitly enabled only when CAVRA_GO_BACKEND_MODE is shadow or enforce.",
        ),
        _check(
            "go_runtime_binary",
            runtime_exists,
            "CAVRA_GO_RUNTIME_PATH points to a local cavra-runtime binary.",
            path=config.runtime_path,
        ),
        _check(
            "go_runtime_policy",
            policy_exists,
            "CAVRA_GO_RUNTIME_POLICY points to compiled policy JSON generated by cavra policy compile.",
            path=config.policy_path,
        ),
        _check(
            "go_runtime_registry",
            registry_exists,
            "Optional CAVRA_GO_RUNTIME_REGISTRY path is present when configured.",
            path=config.registry_path,
        ),
        _check(
            "python_fallback",
            True,
            "Python remains authoritative and is used when Go errors, times out, or diverges.",
        ),
        _check(
            "parity_gate",
            True,
            "Go enforcement is accepted only when decision, rule_id, and severity match Python.",
        ),
    ]
    if config.mode == GO_BACKEND_DISABLED:
        status = "disabled"
    elif all(item["status"] == "pass" for item in checks):
        status = "ready"
    else:
        status = "needs_attention"
    return {
        "schema_version": "cavra.go-backend-pilot.readiness.v1",
        "mode": config.mode,
        "status": status,
        "runtime_path": config.runtime_path,
        "policy_path": config.policy_path,
        "registry_path": config.registry_path,
        "timeout_seconds": config.timeout_seconds,
        "checks": checks,
        "operator_notes": [
            "Leave CAVRA_GO_BACKEND_MODE=disabled unless the environment has current parity evidence.",
            "Use shadow mode first; enforce mode still falls back to Python on mismatch or runtime failure.",
            "Attach this readiness report to deployment evidence before piloting Go in CI or workstation paths.",
        ],
    }


def evaluate_with_go_pilot(
    request: dict[str, Any],
    *,
    config: GoBackendConfig | None = None,
) -> dict[str, Any]:
    config = config or go_backend_config_from_env()
    python_decision = _python_decision(request)
    result: dict[str, Any] = {
        "schema_version": "cavra.go-backend-pilot.evaluation.v1",
        "backend_mode": config.mode,
        "selected_backend": "python",
        "fallback_used": False,
        "fallback_reason": "",
        "parity_match": None,
        "python_decision": python_decision.to_dict(),
        "go_decision": None,
        "effective_decision": python_decision.to_dict(),
    }
    if not config.enabled:
        result["fallback_reason"] = "go backend pilot is disabled"
        return result
    readiness = go_backend_readiness_report(config)
    blocking = [item for item in readiness["checks"] if item["status"] != "pass" and item["id"] != "go_backend_opt_in"]
    if blocking:
        result["fallback_used"] = True
        result["fallback_reason"] = "go backend readiness check failed"
        result["readiness"] = readiness
        return result
    try:
        go_decision = _run_go_runtime(request, config)
    except (subprocess.SubprocessError, OSError, json.JSONDecodeError) as exc:
        result["fallback_used"] = True
        result["fallback_reason"] = f"go runtime failed: {exc}"
        result["readiness"] = readiness
        return result
    result["go_decision"] = go_decision
    parity_match = _decisions_match(python_decision.to_dict(), go_decision)
    result["parity_match"] = parity_match
    if not parity_match:
        result["fallback_used"] = True
        result["fallback_reason"] = "go decision diverged from Python parity gate"
        return result
    if config.mode == GO_BACKEND_ENFORCE:
        result["selected_backend"] = "go"
        result["effective_decision"] = go_decision
    return result


def _python_decision(request: dict[str, Any]) -> ActionDecision:
    guard = RuntimeGuard(
        policy_pack=str(request.get("policy_pack") or "cavra-ai-agent-baseline"),
        session_id=str(request.get("session_id", "local")),
        agent_id=str(request.get("agent_id", "unknown-agent")),
        actor=str(request.get("actor", "ai-agent")),
    )
    action_type = str(request.get("action_type", ""))
    target = str(request.get("target", ""))
    if action_type == "read_file":
        return guard.evaluate_file_access(Path(target), "read")
    if action_type == "write_file":
        return guard.evaluate_file_access(Path(target), "write")
    if action_type == "execute_command":
        return guard.evaluate_command(target)
    if action_type == "git_operation":
        return guard.evaluate_git_action(str(request.get("operation", "push")), target)
    if action_type == "mcp_tool_call":
        return guard.evaluate_mcp_tool_call(
            str(request.get("server", target)),
            str(request.get("tool", "unknown")),
            str(request.get("capability", "")) or None,
        )
    if action_type == "release_governance_record":
        record = request.get("record") or request.get("release_governance")
        return guard.evaluate_release_governance_record(
            record if isinstance(record, dict) else {},
            target=target or None,
            requested_operation=str(request.get("operation", request.get("requested_operation", "verify"))),
        )
    return ActionDecision(
        decision="require_approval",
        reason="Unknown action type; review required.",
        session_id=str(request.get("session_id", "local")),
        agent_id=str(request.get("agent_id", "unknown-agent")),
        actor=str(request.get("actor", "ai-agent")),
        action_type=action_type or "unknown",
        target=target,
        requested_operation=str(request.get("operation", "")),
        policy_pack=str(request.get("policy_pack") or "cavra-ai-agent-baseline"),
        policy_id=str(request.get("policy_pack") or "cavra-ai-agent-baseline"),
        rule_id="runtime.default.require_approval",
        severity="medium",
        approver_group="Repository Owners",
    )


def _run_go_runtime(request: dict[str, Any], config: GoBackendConfig) -> dict[str, Any]:
    command = [config.runtime_path, "--policy", config.policy_path]
    if config.registry_path:
        command.extend(["--registry", config.registry_path])
    completed = subprocess.run(
        command,
        input=json.dumps(request),
        text=True,
        capture_output=True,
        timeout=config.timeout_seconds,
        check=True,
    )
    return json.loads(completed.stdout)


def _decisions_match(python_decision: dict[str, Any], go_decision: dict[str, Any]) -> bool:
    return all(
        python_decision.get(field) == go_decision.get(field)
        for field in ("decision", "rule_id", "severity")
    )


def _normalized_mode(value: str) -> str:
    mode = value.strip().lower() or GO_BACKEND_DISABLED
    return mode if mode in GO_BACKEND_MODES else GO_BACKEND_DISABLED


def _float_env(name: str, default: float) -> float:
    try:
        return float(os.environ.get(name, default))
    except (TypeError, ValueError):
        return default


def _check(check_id: str, passed: bool, message: str, **extra: Any) -> dict[str, Any]:
    return {"id": check_id, "status": "pass" if passed else "warn", "message": message, **extra}
