from __future__ import annotations

import copy
import json
import os
import smtplib
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from cavra.activity import ActivityStore
from cavra.policy_authoring import build_policy_pack_draft
from cavra.policy_registry import PolicyRegistry
from cavra.runtime import RuntimeGuard


SETUP_SCHEMA_VERSION = "cavra.setup-state.v1"
SETUP_VALIDATION_SCHEMA_VERSION = "cavra.setup-validation.v1"
DEMO_WORKSPACE_SCHEMA_VERSION = "cavra.demo-workspace.v1"
POLICY_ACTION_CATALOG_SCHEMA_VERSION = "cavra.policy-action-catalog.v1"
SMTP_TEST_SCHEMA_VERSION = "cavra.smtp-test.v1"

DEFAULT_POLICY_PACK = "cavra-ai-agent-baseline"
DEFAULT_SETUP_STATE_PATH = Path(".cavra/setup-state.json")
DEFAULT_DEMO_WORKSPACE_PATH = Path(".cavra/demo-workspace")

DEMO_FILES: dict[str, str] = {
    ".env": """# Fake demo values only.
DEMO_TOKEN=not-a-real-secret
DEMO_SERVICE_URL=https://example.invalid
""",
    "README.md": """# CAVRA Demo Workspace

This workspace is generated by `cavra setup demo-env`.

It contains safe sample files and intentionally risky-looking paths so Claude
Code, Codex, Copilot workflows, and manual CLI tests can prove CAVRA policy
decisions without using real secrets or production infrastructure.
""",
    "safe-notes.md": """# Safe Notes

This file should be allowed by the default CAVRA policy.
""",
    "fake.env": """# Fake demo values only.
DEMO_API_KEY=not-a-real-secret
DEMO_DATABASE_URL=postgres://demo:demo@example.invalid/demo
""",
    "iam/admin-role.tf": """# Demo IAM admin role change.
# This file is intentionally under iam/ so default policy requires approval.
resource "example_iam_role" "admin" {
  name = "demo-admin"
}
""",
    "terraform/main.tf": """# Demo Terraform configuration.
terraform {
  required_version = ">= 1.5.0"
}

resource "null_resource" "demo" {}
""",
    "kubernetes/delete-prod.yaml": """# Demo manifest for destructive-action testing only.
apiVersion: v1
kind: Namespace
metadata:
  name: prod
""",
    "scripts/deploy.sh": """#!/usr/bin/env sh
set -eu
echo "demo deploy script; do not use for production"
terraform plan
""",
}

DEFAULT_SCENARIOS: list[dict[str, Any]] = [
    {
        "id": "read-safe-file",
        "label": "Read safe file",
        "action_type": "read_file",
        "target": "README.md",
        "expected_decision": "allow",
    },
    {
        "id": "read-secret-file",
        "label": "Read fake secret file",
        "action_type": "read_file",
        "target": ".env",
        "expected_decision": "block",
    },
    {
        "id": "terraform-plan",
        "label": "Terraform plan",
        "action_type": "execute_command",
        "target": "terraform plan",
        "expected_decision": "allow",
    },
    {
        "id": "terraform-apply",
        "label": "Terraform apply",
        "action_type": "execute_command",
        "target": "terraform apply -auto-approve",
        "expected_decision": "block",
    },
    {
        "id": "write-admin-role",
        "label": "Write IAM admin role",
        "action_type": "write_file",
        "target": "iam/admin-role.tf",
        "expected_decision": "require_approval",
    },
    {
        "id": "delete-kubernetes-prod",
        "label": "Delete Kubernetes production namespace",
        "action_type": "execute_command",
        "target": "kubectl delete namespace prod",
        "expected_decision": "block",
    },
    {
        "id": "push-main",
        "label": "Push protected branch",
        "action_type": "git_operation",
        "target": "origin/main",
        "operation": "push",
        "expected_decision": "block",
    },
    {
        "id": "unknown-mcp-server",
        "label": "Unknown MCP filesystem server",
        "action_type": "mcp_tool_call",
        "server": "unknown-filesystem",
        "tool": "read_file",
        "capability": "filesystem",
        "expected_decision": "block",
    },
]


def setup_state_path(path: Path | None = None) -> Path:
    configured = os.environ.get("CAVRA_SETUP_STATE_STORE")
    return path or (Path(configured) if configured else DEFAULT_SETUP_STATE_PATH)


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def default_setup_state(
    *,
    workspace_name: str = "local-community",
    policy_pack: str = DEFAULT_POLICY_PACK,
    demo_workspace: Path = DEFAULT_DEMO_WORKSPACE_PATH,
) -> dict[str, Any]:
    return {
        "schema_version": SETUP_SCHEMA_VERSION,
        "product": "CAVRA",
        "setup_complete": False,
        "created_at": utc_now(),
        "updated_at": utc_now(),
        "workspace": {
            "name": workspace_name,
            "mode": os.environ.get("CAVRA_EDITION", "community"),
            "environment": "local",
        },
        "policy": {
            "default_pack": policy_pack,
            "mode": "enforce",
            "editable_catalog": True,
        },
        "reports": {
            "smtp_enabled": False,
            "host": "",
            "port": 587,
            "username": "",
            "from_email": "",
            "recipient_allowlist": [],
            "password_ref": "CAVRA_REPORT_SMTP_PASSWORD",
            "delivery_mode": "not_configured",
        },
        "evidence": {
            "store": "local",
            "artifact_root": ".cavra/evidence",
        },
        "aispm": {
            "enabled": True,
            "refresh_mode": "activity-store",
        },
        "agents": {
            "claude_code": {"enabled": True, "integration": "mcp-or-guarded-wrapper"},
            "codex": {"enabled": True, "integration": "mcp-or-guarded-wrapper"},
            "copilot": {"enabled": False, "integration": "ci-or-guarded-wrapper"},
        },
        "demo": {
            "enabled": True,
            "workspace_path": str(demo_workspace),
            "scenario_count": len(DEFAULT_SCENARIOS),
            "scenarios": copy.deepcopy(DEFAULT_SCENARIOS),
        },
        "operator_notes": [
            "Defaults are safe for local Community validation.",
            "SMTP/report delivery requires operator configuration before live email delivery.",
            "Policy edits should use draft, approval, and publish workflows before rollout.",
        ],
    }


def load_setup_state(path: Path | None = None) -> dict[str, Any] | None:
    target = setup_state_path(path)
    if not target.exists():
        return None
    payload = json.loads(target.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError("setup state must be a JSON object")
    return payload


def save_setup_state(state: dict[str, Any], path: Path | None = None) -> dict[str, Any]:
    target = setup_state_path(path)
    payload = copy.deepcopy(state)
    payload["updated_at"] = utc_now()
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return payload


def setup_status(path: Path | None = None) -> dict[str, Any]:
    target = setup_state_path(path)
    state = load_setup_state(target)
    policy_pack = _state_policy_pack(state)
    smtp = (state or {}).get("reports", {}) if isinstance((state or {}).get("reports"), dict) else {}
    demo_path = Path((state or {}).get("demo", {}).get("workspace_path", DEFAULT_DEMO_WORKSPACE_PATH)) if state else DEFAULT_DEMO_WORKSPACE_PATH
    return {
        "schema_version": "cavra.setup-status.v1",
        "product": "CAVRA",
        "configured": state is not None,
        "setup_complete": bool((state or {}).get("setup_complete")),
        "state_path": str(target),
        "workspace": (state or {}).get("workspace", {}),
        "policy": {
            "default_pack": policy_pack,
            "available": _policy_pack_available(policy_pack),
        },
        "demo": {
            "workspace_path": str(demo_path),
            "exists": demo_path.exists(),
        },
        "reports": {
            "smtp_enabled": bool(smtp.get("smtp_enabled")),
            "delivery_mode": smtp.get("delivery_mode", "not_configured"),
            "from_email": smtp.get("from_email", ""),
            "recipient_count": len(smtp.get("recipient_allowlist", []) or []),
            "password_ref": smtp.get("password_ref", "CAVRA_REPORT_SMTP_PASSWORD"),
        },
        "next_steps": _setup_next_steps(state, demo_path, policy_pack),
    }


def bootstrap_setup(
    *,
    path: Path | None = None,
    workspace_name: str = "local-community",
    policy_pack: str = DEFAULT_POLICY_PACK,
    overwrite: bool = False,
    complete: bool = False,
) -> dict[str, Any]:
    target = setup_state_path(path)
    if target.exists() and not overwrite:
        state = load_setup_state(target)
        return {
            "schema_version": "cavra.setup-bootstrap.v1",
            "product": "CAVRA",
            "status": "exists",
            "state_path": str(target),
            "state": state,
            "operator_notes": ["Existing setup state was preserved. Use overwrite to regenerate defaults."],
        }
    state = default_setup_state(workspace_name=workspace_name, policy_pack=policy_pack)
    state["setup_complete"] = bool(complete)
    saved = save_setup_state(state, target)
    return {
        "schema_version": "cavra.setup-bootstrap.v1",
        "product": "CAVRA",
        "status": "created",
        "state_path": str(target),
        "state": saved,
        "operator_notes": [
            "Default CAVRA setup state has been created.",
            "Run demo workspace generation and setup validation before connecting AI agents.",
        ],
    }


def complete_setup(path: Path | None = None) -> dict[str, Any]:
    state = load_setup_state(path) or default_setup_state()
    state["setup_complete"] = True
    saved = save_setup_state(state, path)
    return {
        "schema_version": "cavra.setup-complete.v1",
        "product": "CAVRA",
        "status": "complete",
        "state": saved,
    }


def create_demo_workspace(output: Path | None = None, *, overwrite: bool = False) -> dict[str, Any]:
    root = output or DEFAULT_DEMO_WORKSPACE_PATH
    written: list[str] = []
    skipped: list[str] = []
    for relative, content in DEMO_FILES.items():
        path = root / relative
        if path.exists() and not overwrite:
            skipped.append(str(path))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        if path.name == "deploy.sh":
            path.chmod(0o755)
        written.append(str(path))
    state = load_setup_state() or default_setup_state(demo_workspace=root)
    state.setdefault("demo", {})
    state["demo"]["enabled"] = True
    state["demo"]["workspace_path"] = str(root)
    state["demo"]["scenario_count"] = len(DEFAULT_SCENARIOS)
    state["demo"]["scenarios"] = copy.deepcopy(DEFAULT_SCENARIOS)
    saved = save_setup_state(state)
    return {
        "schema_version": DEMO_WORKSPACE_SCHEMA_VERSION,
        "product": "CAVRA",
        "workspace_path": str(root),
        "written": written,
        "skipped": skipped,
        "scenarios": copy.deepcopy(DEFAULT_SCENARIOS),
        "state_path": str(setup_state_path()),
        "state": saved,
        "operator_notes": [
            "Demo workspace uses fake sample data only.",
            "Use this workspace for manual agent validation, not production workloads.",
        ],
    }


def validate_setup(
    *,
    path: Path | None = None,
    record_decisions: bool = False,
    activity_store: ActivityStore | None = None,
    session_id: str | None = None,
) -> dict[str, Any]:
    state = load_setup_state(path) or default_setup_state()
    policy_pack = _state_policy_pack(state)
    guard = RuntimeGuard(
        policy_pack=policy_pack,
        session_id=session_id or f"setup-validation-{uuid.uuid4().hex[:8]}",
        agent_id="cavra-setup-validator",
        actor="cavra-setup",
    )
    scenario_results = []
    for scenario in state.get("demo", {}).get("scenarios", DEFAULT_SCENARIOS):
        decision = _evaluate_scenario(guard, scenario).to_dict()
        passed = decision["decision"] == scenario.get("expected_decision")
        scenario_results.append(
            {
                "scenario_id": scenario.get("id"),
                "label": scenario.get("label"),
                "expected_decision": scenario.get("expected_decision"),
                "actual_decision": decision["decision"],
                "passed": passed,
                "decision": decision,
            }
        )
        if record_decisions and activity_store is not None:
            activity_store.upsert_decision({**decision, "repository": "cavra-demo-workspace"})
    checks = [
        _check("setup_state", True, "Setup state can be loaded or defaulted."),
        _check("policy_pack", _policy_pack_available(policy_pack), f"Policy pack {policy_pack} is discoverable."),
        _check(
            "demo_workspace",
            Path(state.get("demo", {}).get("workspace_path", DEFAULT_DEMO_WORKSPACE_PATH)).exists(),
            "Demo workspace exists.",
        ),
        _check(
            "smtp_configuration",
            bool(state.get("reports", {}).get("smtp_enabled")) or state.get("reports", {}).get("delivery_mode") == "not_configured",
            "SMTP is configured or explicitly not configured.",
        ),
        _check("aispm_enabled", bool(state.get("aispm", {}).get("enabled", True)), "AISPM is enabled in setup state."),
        _check("scenario_decisions", all(item["passed"] for item in scenario_results), "Default validation scenarios match expected decisions."),
    ]
    return {
        "schema_version": SETUP_VALIDATION_SCHEMA_VERSION,
        "product": "CAVRA",
        "generated_at": utc_now(),
        "status": "ready" if all(check["status"] == "pass" for check in checks) else "needs_attention",
        "state_path": str(setup_state_path(path)),
        "policy_pack": policy_pack,
        "checks": checks,
        "scenarios": scenario_results,
        "summary": {
            "check_count": len(checks),
            "pass_count": sum(1 for check in checks if check["status"] == "pass"),
            "scenario_count": len(scenario_results),
            "scenario_pass_count": sum(1 for item in scenario_results if item["passed"]),
        },
    }


def build_policy_action_catalog(policy_pack: str = DEFAULT_POLICY_PACK) -> dict[str, Any]:
    policy = PolicyRegistry().load_policy(policy_pack)
    items = []
    for section, actions in (
        ("filesystem", ("block_read", "block_write", "require_approval_write")),
        ("commands", ("block", "allow", "require_approval")),
        ("mcp", ("allowed_servers", "blocked_servers")),
    ):
        payload = policy.get(section, {}) if isinstance(policy.get(section), dict) else {}
        for action in actions:
            for index, value in enumerate(payload.get(action, []) or []):
                items.append(
                    {
                        "id": f"{section}:{action}:{index}",
                        "section": section,
                        "action": action,
                        "value": str(value),
                        "policy_pack": policy_pack,
                        "editable_via": "policy-draft",
                    }
                )
    return {
        "schema_version": POLICY_ACTION_CATALOG_SCHEMA_VERSION,
        "product": "CAVRA",
        "policy_pack": policy_pack,
        "total": len(items),
        "items": items,
        "operator_notes": [
            "Catalog entries are derived from the active policy pack.",
            "Create, update, or delete requests return a policy draft and do not bypass approval-bound publishing.",
        ],
    }


def plan_policy_action_change(payload: dict[str, Any], *, policy_pack: str = DEFAULT_POLICY_PACK) -> dict[str, Any]:
    operation = str(payload.get("operation", "add"))
    if operation not in {"add", "update", "delete"}:
        raise ValueError("operation must be add, update, or delete")
    section = str(payload.get("section", "commands"))
    action = str(payload.get("action", "block"))
    value = str(payload.get("value", ""))
    if not value and operation in {"add", "update"}:
        raise ValueError("value is required for add or update")
    policy = copy.deepcopy(PolicyRegistry().load_policy(policy_pack))
    if section not in policy or not isinstance(policy.get(section), dict):
        policy[section] = {}
    values = [str(item) for item in policy[section].get(action, []) or []]
    if operation == "add":
        if value not in values:
            values.append(value)
    elif operation == "update":
        index = int(payload.get("index", -1))
        if index < 0 or index >= len(values):
            raise ValueError("valid index is required for update")
        values[index] = value
    elif operation == "delete":
        index = int(payload.get("index", -1))
        if index < 0 or index >= len(values):
            raise ValueError("valid index is required for delete")
        values.pop(index)
    policy[section][action] = values
    draft_payload = {
        "metadata": policy["metadata"],
        **{key: value for key, value in policy.items() if key != "metadata"},
    }
    draft = build_policy_pack_draft(draft_payload)
    return {
        "schema_version": "cavra.policy-action-change-plan.v1",
        "product": "CAVRA",
        "operation": operation,
        "policy_pack": policy_pack,
        "change": {
            "section": section,
            "action": action,
            "value": value,
            "index": payload.get("index"),
        },
        "draft": draft,
        "publish_required": True,
        "operator_notes": [
            "Review the draft, request approval, and publish through policy-pack publish workflow.",
            "This endpoint does not write directly to the active policy directory.",
        ],
    }


def test_policy_action(payload: dict[str, Any], *, policy_pack: str = DEFAULT_POLICY_PACK) -> dict[str, Any]:
    guard = RuntimeGuard(policy_pack=policy_pack)
    decision = _evaluate_scenario(
        guard,
        {
            "action_type": payload.get("action_type", "execute_command"),
            "target": payload.get("target", payload.get("value", "")),
            "operation": payload.get("operation", "push"),
            "server": payload.get("server", "unknown-filesystem"),
            "tool": payload.get("tool", "read_file"),
            "capability": payload.get("capability", "filesystem"),
        },
    ).to_dict()
    return {
        "schema_version": "cavra.policy-action-test.v1",
        "product": "CAVRA",
        "policy_pack": policy_pack,
        "input": payload,
        "decision": decision,
    }


def smtp_test_plan(payload: dict[str, Any], *, live: bool = False) -> dict[str, Any]:
    host = str(payload.get("host", "")).strip()
    port = int(payload.get("port", 587))
    from_email = str(payload.get("from_email", "")).strip()
    recipients = payload.get("recipient_allowlist", payload.get("recipients", []))
    if isinstance(recipients, str):
        recipients = [item.strip() for item in recipients.split(",") if item.strip()]
    password_ref = str(payload.get("password_ref", "CAVRA_REPORT_SMTP_PASSWORD"))
    checks = [
        _check("host", bool(host), "SMTP host is provided."),
        _check("port", port > 0, "SMTP port is provided."),
        _check("from_email", "@" in from_email, "From email appears valid."),
        _check("recipient_allowlist", bool(recipients), "At least one recipient is allowed."),
        _check("password_ref", bool(password_ref), "Password secret reference is provided."),
    ]
    live_result: dict[str, Any] | None = None
    if live and all(check["status"] == "pass" for check in checks):
        live_result = _smtp_live_check(host=host, port=port)
        checks.append(_check("smtp_connection", live_result["ok"], live_result["message"]))
    return {
        "schema_version": SMTP_TEST_SCHEMA_VERSION,
        "product": "CAVRA",
        "status": "ready" if all(check["status"] == "pass" for check in checks) else "needs_attention",
        "live": live,
        "checks": checks,
        "configuration": {
            "host": host,
            "port": port,
            "from_email": from_email,
            "recipient_count": len(recipients),
            "password_ref": password_ref,
        },
        "live_result": live_result,
        "operator_notes": [
            "No SMTP password is stored in setup state.",
            "Set the secret value in the deployment environment or secret manager referenced by password_ref.",
        ],
    }


def update_smtp_setup(payload: dict[str, Any], *, path: Path | None = None) -> dict[str, Any]:
    state = load_setup_state(path) or default_setup_state()
    plan = smtp_test_plan(payload, live=bool(payload.get("live")))
    state["reports"] = {
        **state.get("reports", {}),
        "smtp_enabled": plan["status"] == "ready",
        "host": plan["configuration"]["host"],
        "port": plan["configuration"]["port"],
        "from_email": plan["configuration"]["from_email"],
        "recipient_allowlist": payload.get("recipient_allowlist", payload.get("recipients", [])),
        "password_ref": plan["configuration"]["password_ref"],
        "delivery_mode": "smtp_configured" if plan["status"] == "ready" else "needs_attention",
    }
    saved = save_setup_state(state, path)
    return {
        "schema_version": "cavra.smtp-setup.v1",
        "product": "CAVRA",
        "status": plan["status"],
        "smtp_test": plan,
        "state": saved,
    }


def _state_policy_pack(state: dict[str, Any] | None) -> str:
    if not state:
        return DEFAULT_POLICY_PACK
    policy = state.get("policy", {}) if isinstance(state.get("policy"), dict) else {}
    return str(policy.get("default_pack") or DEFAULT_POLICY_PACK)


def _policy_pack_available(policy_pack: str) -> bool:
    try:
        PolicyRegistry().get_policy_pack(policy_pack)
        return True
    except Exception:
        return False


def _setup_next_steps(state: dict[str, Any] | None, demo_path: Path, policy_pack: str) -> list[str]:
    steps: list[str] = []
    if state is None:
        steps.append("Run setup bootstrap to create default setup state.")
    if not demo_path.exists():
        steps.append("Generate the demo workspace.")
    if not _policy_pack_available(policy_pack):
        steps.append(f"Make policy pack {policy_pack} available.")
    if not state or not state.get("reports", {}).get("smtp_enabled"):
        steps.append("Configure SMTP/report delivery when live reports are required.")
    if state and not state.get("setup_complete"):
        steps.append("Run setup validation and mark setup complete.")
    return steps


def _evaluate_scenario(guard: RuntimeGuard, scenario: dict[str, Any]) -> Any:
    action_type = scenario.get("action_type")
    target = str(scenario.get("target", ""))
    if action_type == "read_file":
        return guard.evaluate_file_access(Path(target), "read")
    if action_type == "write_file":
        return guard.evaluate_file_access(Path(target), "write")
    if action_type == "execute_command":
        return guard.evaluate_command(target)
    if action_type == "git_operation":
        return guard.evaluate_git_action(str(scenario.get("operation", "push")), target)
    if action_type == "mcp_tool_call":
        return guard.evaluate_mcp_tool_call(
            str(scenario.get("server", "unknown-filesystem")),
            str(scenario.get("tool", "read_file")),
            str(scenario.get("capability", "filesystem")),
        )
    return guard.evaluate_command(target)


def _check(name: str, ok: bool, message: str, **extra: Any) -> dict[str, Any]:
    return {"name": name, "status": "pass" if ok else "fail", "message": message, **extra}


def _smtp_live_check(*, host: str, port: int) -> dict[str, Any]:
    try:
        with smtplib.SMTP(host, port, timeout=10) as client:
            client.ehlo()
            if port == 587:
                client.starttls()
                client.ehlo()
        return {"ok": True, "message": "SMTP server accepted connection and EHLO."}
    except Exception as exc:
        return {"ok": False, "message": f"SMTP connection failed: {exc}"}
