{{- if and (not .Values.existingSecret) (or .Values.secretEnv .Values.externalPostgresql.password) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cavra.fullname" . }}
  labels:
    {{- include "cavra.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if .Values.externalPostgresql.password }}
  CAVRA_POSTGRES_PASSWORD: {{ .Values.externalPostgresql.password | quote }}
  {{- end }}
{{- end }}
