#!/usr/bin/env python3
"""Validate the public CAVRA sandbox portal contract."""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def read(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8")


def require_file(path: str, failures: list[str]) -> None:
    if not (ROOT / path).is_file():
        failures.append(f"missing required file: {path}")


def require(text: str, needle: str, label: str, failures: list[str]) -> None:
    if needle not in text:
        failures.append(f"missing {label}: {needle}")


def require_any(texts: list[str], needle: str, label: str, failures: list[str]) -> None:
    if not any(needle in text for text in texts):
        failures.append(f"missing {label}: {needle}")


def main() -> int:
    failures: list[str] = []
    required_files = [
        "apps/sandbox-ui/index.html",
        "apps/sandbox-ui/styles.css",
        "apps/sandbox-ui/sandbox.js",
        "apps/sandbox-ui/brand/favicon.svg",
        "apps/sandbox-ui/brand/cavra-mark.svg",
        "apps/sandbox-ui/brand/cavra-logo-horizontal.svg",
        "assets/brand/cavra-logo-horizontal.svg",
        "docs/diagrams/c4-container.svg",
        ".github/workflows/deploy-sandbox.yml",
        "docs/sandbox-portal-redesign.md",
        "docs/sandbox-portal-smoke-validation.md",
        "docs/wiki/CAVRA-Developer-Portal-Redesign.md",
        "docs/wiki/CAVRA-Developer-Portal-Smoke-Validation.md",
    ]
    for path in required_files:
        require_file(path, failures)

    if failures:
        for failure in failures:
            print(failure)
        return 1

    html = read("apps/sandbox-ui/index.html")
    css = read("apps/sandbox-ui/styles.css")
    js = read("apps/sandbox-ui/sandbox.js")
    deploy = read(".github/workflows/deploy-sandbox.yml")
    readme = read("README.md")
    wiki_home = read("docs/wiki/Home.md")
    redesign_doc = read("docs/sandbox-portal-redesign.md")
    smoke_doc = read("docs/sandbox-portal-smoke-validation.md")
    wiki_smoke_doc = read("docs/wiki/CAVRA-Developer-Portal-Smoke-Validation.md")

    routes = [
        "dashboard",
        "ai-posture",
        "architecture",
        "policy-engine",
        "evidence",
        "integrations",
        "compliance",
        "use-cases",
        "operator-experience",
        "enterprise-trial",
        "documentation",
        "roadmap",
    ]
    for route in routes:
        require_any([html, js], route, "portal route", failures)

    required_html = [
        'class="top-shell"',
        'class="sidebar"',
        'class="portal-shell"',
        'class="portal-main"',
        'class="mobile-bottom"',
        'class="command-palette"',
        'class="architecture-workbench"',
        'id="portalNav"',
        'id="mobileNav"',
        'id="toc"',
        'id="commandPalette"',
        'id="commandSearch"',
        'id="commandResults"',
        'id="mobileDrawer"',
        'id="openMobileNav"',
        'id="closeMobileNav"',
        'id="mobileSearch"',
        'id="themeSelect"',
        'id="mobileThemeSelect"',
        "data-theme-select",
        'id="architectureMap"',
        'id="nodeInspector"',
        'id="aispmSourceBadge"',
        'id="refreshAispm"',
        'id="aispmOverviewCards"',
        'id="aispmTrialReadinessChecklist"',
        'id="copyAispmTrialReadinessSummary"',
        'id="downloadAispmTrialReadinessPacket"',
        'id="aispmTrialReadinessStatus"',
        'id="aispmEvaluatorHandoff"',
        'id="aispmTrialJourney"',
        'id="aispmTrialCloseoutEvidence"',
        'id="aispmTrialFeedbackIntake"',
        'id="aispmTrialOutcomeSummary"',
        'id="copyAispmTrialReviewPacket"',
        'id="downloadAispmTrialReviewPacket"',
        'id="aispmTrialReviewPacketStatus"',
        'id="aispmTrialReviewPacketIntegrity"',
        'id="aispmTrialProcurementReadiness"',
        'id="aispmTrialPilotScope"',
        'id="copyAispmTrialPilotScopePacket"',
        'id="downloadAispmTrialPilotScopePacket"',
        'id="aispmTrialPilotScopeStatus"',
        'id="aispmPilotApprovalChecklist"',
        'id="copyAispmPilotApprovalPacket"',
        'id="downloadAispmPilotApprovalPacket"',
        'id="aispmPilotApprovalStatus"',
        'id="aispmPilotLaunchReadiness"',
        'id="copyAispmPilotLaunchDecisionPacket"',
        'id="downloadAispmPilotLaunchDecisionPacket"',
        'id="aispmPilotLaunchStatus"',
        'id="aispmPilotEvidenceRoom"',
        'id="copyAispmPilotEvidenceRoomPacket"',
        'id="downloadAispmPilotEvidenceRoomPacket"',
        'id="aispmPilotEvidenceRoomStatus"',
        'id="aispmEvidenceReviewerChecklist"',
        'id="copyAispmEvidenceReviewerChecklistPacket"',
        'id="downloadAispmEvidenceReviewerChecklistPacket"',
        'id="aispmEvidenceReviewerChecklistStatus"',
        'id="aispmPilotExceptionRegister"',
        'id="copyAispmPilotExceptionRegisterPacket"',
        'id="downloadAispmPilotExceptionRegisterPacket"',
        'id="aispmPilotExceptionStatus"',
        'id="aispmPilotRiskAcceptanceSummary"',
        'id="copyAispmPilotRiskAcceptancePacket"',
        'id="downloadAispmPilotRiskAcceptancePacket"',
        'id="aispmPilotRiskAcceptanceStatus"',
        'id="aispmPilotLaunchBoardPack"',
        'id="aispmPilotLaunchBoardPackManifest"',
        'id="copyAispmPilotLaunchBoardPackPacket"',
        'id="downloadAispmPilotLaunchBoardPackPacket"',
        'id="aispmPilotLaunchBoardPackStatus"',
        'id="aispmPilotControlReadiness"',
        'id="copyAispmPilotControlReadinessPacket"',
        'id="downloadAispmPilotControlReadinessPacket"',
        'id="aispmPilotControlStatus"',
        'id="aispmReleaseEvidenceIndex"',
        'id="aispmReleaseEvidenceManifest"',
        'id="copyAispmReleaseEvidenceIndexPacket"',
        'id="downloadAispmReleaseEvidenceIndexPacket"',
        'id="aispmReleaseEvidenceStatus"',
        'id="aispmHostedReleaseStatus"',
        'id="aispmHostedReleaseChecklist"',
        'id="copyAispmHostedReleaseStatusPacket"',
        'id="downloadAispmHostedReleaseStatusPacket"',
        'id="aispmHostedReleaseStatusLine"',
        'id="aispmAgentCards"',
        'id="aispmFindings"',
        'id="aispmControlCoverage"',
        'id="aispmNearMisses"',
        'id="refreshAispmContextGaps"',
        'id="aispmContextGapSummary"',
        'id="aispmPolicyContextGaps"',
        'id="refreshAispmForecasts"',
        'id="aispmForecastSummary"',
        'id="aispmPreActionForecasts"',
        'id="refreshAispmIntentDrift"',
        'id="aispmIntentDriftSummary"',
        'id="aispmIntentActionDrift"',
        'id="refreshAispmToolGraph"',
        'id="aispmToolGraphSummary"',
        'id="aispmToolGraphNodes"',
        'id="aispmToolGraphEdges"',
        'id="refreshAispmBlastRadius"',
        'id="aispmBlastRadiusSummary"',
        'id="aispmAgentBlastRadius"',
        'id="refreshAispmCoverageHeatmap"',
        'id="aispmCoverageHeatmapSummary"',
        'id="aispmCoverageHeatmapRows"',
        'id="refreshAispmEvidenceConfidence"',
        'id="aispmEvidenceConfidenceSummary"',
        'id="aispmEvidenceConfidenceRows"',
        'id="refreshAispmEvidenceFreshness"',
        'id="aispmEvidenceFreshnessSummary"',
        'id="aispmEvidenceFreshnessRows"',
        'id="refreshAispmExecutiveNarrative"',
        'id="aispmExecutiveNarrativeSummary"',
        'id="aispmExecutiveNarrative"',
        'id="refreshAispmReplayPolicy"',
        'id="aispmReplayPolicySummary"',
        'id="aispmReplayPolicyReviewWorkflow"',
        'id="aispmReplayPolicyReviewPacketStatus"',
        'id="copyAispmReplayPolicyReviewPacket"',
        'id="downloadAispmReplayPolicyReviewPacket"',
        'id="aispmReplayPolicyPrGuidance"',
        'id="aispmReplayPolicyCiGate"',
        'id="aispmReplayPolicyCiGateSummary"',
        'id="aispmReplayPolicyCiGateStatus"',
        'id="copyAispmReplayPolicyCiGateReadiness"',
        'id="downloadAispmReplayPolicyCiGateReadiness"',
        'id="aispmReplayPolicyCiGateRolloutStatus"',
        'id="copyAispmReplayPolicyCiGateRollout"',
        'id="downloadAispmReplayPolicyCiGateRollout"',
        'id="aispmReplayPolicyCiGateRollout"',
        'id="aispmReplayPolicyCiGateAuditStatus"',
        'id="copyAispmReplayPolicyCiGateAuditPacket"',
        'id="downloadAispmReplayPolicyCiGateAuditPacket"',
        'id="aispmReplayPolicyCiGateAuditPacket"',
        'id="aispmReplayPolicyRecommendations"',
        'id="aispmReplayPolicyDraft"',
        'id="aispmReplayPolicyTestStatus"',
        'id="copyAispmReplayPolicyTests"',
        'id="downloadAispmReplayPolicyTests"',
        'id="aispmReplayPolicyTests"',
        'id="refreshAispmFingerprints"',
        'id="aispmFingerprintSummary"',
        'id="aispmBehaviorFingerprints"',
        'id="aispmTimeline"',
        'id="refreshAispmApprovals"',
        'id="aispmApprovalSummary"',
        'id="aispmApprovalLineage"',
        'id="aispmTraceSession"',
        'id="aispmTraceStatus"',
        'id="aispmTraceSummary"',
        'id="aispmTraceSteps"',
        'id="aispmTraceRedaction"',
        'id="aispmTracePayload"',
        'id="aispmPayload"',
        'id="policyExplorer"',
        'id="evidenceTimeline"',
        'id="integrationCards"',
        'id="complianceFilter"',
        'id="complianceFramework"',
        'id="complianceRows"',
        'id="useCaseCards"',
        'id="operatorPathCards"',
        'id="trialAccessCards"',
        'id="docsNav"',
        'id="roadmapBoard"',
    ]
    for needle in required_html:
        require(html, needle, "portal DOM contract", failures)

    for needle in [
        "routeContent",
        "renderCommandResults",
        "openCommandPalette",
        'type: "Page"',
        'type: "Policy"',
        'type: "Integration"',
        'type: "Control"',
        'type: "Use Case"',
        'type: "Operator Path"',
        'type: "Enterprise Trial"',
        'type: "AI Posture"',
        "AISPM Trial Lab Notebook Readiness",
        "Trial Lab Notebook Readiness Summary",
        "Trial Lab Notebook Readiness JSON",
        "Enterprise Trial Lab Notebook Wiki",
        "AISPM Enterprise Trial Readiness Checklist",
        "applyTheme",
        "normalizeTheme",
        "[data-theme-select]",
    ]:
        require(js, needle, "command palette contract", failures)
    require_any([html, js], "Ctrl K", "command palette shortcut label", failures)

    for needle in [
        "@media (max-width: 900px)",
        ".mobile-bottom",
        ".mobile-drawer",
        ".theme-picker",
        'body[data-theme="classic"]',
        'body[data-theme="retro"]',
        'body[data-theme="executive"]',
        ".fixture-export-actions",
        ".review-workflow-panel",
        ".review-checklist",
        ".pr-guidance-panel",
        ".pr-guidance-grid",
        ".trial-readiness-checklist",
        ".evaluator-handoff-grid",
        ".trial-journey-timeline",
        ".trial-closeout-grid",
        ".trial-feedback-grid",
        ".trial-outcome-grid",
        ".trial-integrity-grid",
        ".procurement-readiness-grid",
        ".pilot-scope-grid",
        ".pilot-approval-grid",
        ".pilot-launch-grid",
        ".pilot-evidence-room-grid",
        ".evidence-reviewer-checklist-grid",
        ".pilot-exception-grid",
        ".risk-acceptance-grid",
        ".board-pack-grid",
        ".board-pack-manifest-grid",
        ".aispm-pilot-control-panel",
        ".pilot-control-grid",
        ".pilot-control-card",
        ".aispm-hosted-release-panel",
        ".hosted-release-status-grid",
        ".hosted-release-checklist-grid",
        ".hosted-release-check-card",
        ".aispm-report-operations-panel",
        ".report-operations-grid",
        ".report-operations-card",
        ".aispm-report-governance-panel",
        ".report-governance-grid",
        ".report-governance-card",
        ".aispm-report-assurance-panel",
        ".report-assurance-grid",
        ".report-assurance-card",
        ".aispm-report-response-panel",
        ".report-response-grid",
        ".report-response-card",
        ".aispm-report-trialops-panel",
        ".report-trialops-grid",
        ".report-trialops-card",
        ".action-buttons",
    ]:
        require(css, needle, "mobile portal CSS", failures)

    for needle in [
        "GitHub",
        "GitLab",
        "Terraform / OpenTofu",
        "Kubernetes",
        "CAVRA",
        "Policy Engine",
        "Evidence Engine",
        "Audit Trail",
        "AWS / Azure / GCP",
        "renderArchitecture",
        "renderNodeInspector",
        "renderAispmDashboard",
        "renderAispmApprovalLineage",
        "loadAispmApprovalLineage",
        "renderAispmBehaviorFingerprints",
        "loadAispmBehaviorFingerprints",
        "renderAispmPolicyContextGaps",
        "loadAispmPolicyContextGaps",
        "renderAispmPreActionForecasts",
        "loadAispmPreActionForecasts",
        "renderAispmIntentActionDrift",
        "loadAispmIntentActionDrift",
        "renderAispmToolChainGraph",
        "loadAispmToolChainGraph",
        "renderAispmAgentBlastRadius",
        "loadAispmAgentBlastRadius",
        "renderAispmControlCoverageHeatmap",
        "loadAispmControlCoverageHeatmap",
        "renderAispmExecutiveNarrative",
        "loadAispmExecutiveNarrative",
        "renderAispmReplayPolicy",
        "loadAispmReplayPolicy",
        "renderAispmReplayPolicyTests",
        "loadAispmReplayPolicyTests",
        "renderAispmReplayPolicyReviewWorkflow",
        "copyAispmReplayPolicyReviewPacket",
        "downloadAispmReplayPolicyReviewPacket",
        "cavra-replay-policy-review-packet.json",
        "renderAispmReplayPolicyPrGuidance",
        "copyAispmReplayPolicyPrApproval",
        "CAVRA replay-to-policy review completed.",
        "renderAispmReplayPolicyCiGate",
        "Replay-To-Policy CI Gate",
        "renderAispmReplayPolicyCiGateSummary",
        "CI Gate Readiness Summary",
        "Action Required",
        "renderAispmReplayPolicyCiGateRolloutChecklist",
        "CI Gate Production Rollout Checklist",
        "cavra-replay-policy-ci-gate-rollout-checklist.md",
        "copyAispmReplayPolicyCiGateRollout",
        "downloadAispmReplayPolicyCiGateRollout",
        "renderAispmReplayPolicyCiGateAuditPacket",
        "CI Gate Rollout Audit Packet",
        "cavra.aispm.replay_to_policy_ci_gate_rollout_audit_packet.v1",
        "cavra-replay-policy-ci-gate-rollout-audit-packet.json",
        "renderAispmReplayPolicyCiGateAuditorView",
        "CI Gate Rollout Auditor View",
        "Auditor conclusion: ready for controlled production rollout",
        "Public safety boundary",
        "Enterprise automation boundary",
        "renderAispmReportCenter",
        "renderAispmTrialReadinessChecklist",
        "copyAispmTrialReadinessSummary",
        "downloadAispmTrialReadinessPacket",
        "handleAispmReportDownload",
        "AISPM Enterprise Trial Readiness Checklist",
        "Enterprise Trial Evaluator Handoff",
        "renderAispmEvaluatorHandoff",
        "Enterprise Trial Evaluation Journey",
        "renderAispmTrialJourney",
        "Request Submitted",
        "Operator Approved",
        "Package Pulled",
        "License Validated",
        "Scenario Executed",
        "Evidence Reviewed",
        "Closeout Verified",
        "AISPM Trial Closeout Evidence",
        "renderAispmTrialCloseoutEvidence",
        "License Expiry",
        "Revocation Check",
        "Package Access Removal",
        "Blocked Runtime Validation",
        "Evidence Packet Archived",
        "Evaluator Feedback",
        "AISPM Trial Feedback Intake",
        "renderAispmTrialFeedbackIntake",
        "Setup Friction",
        "Policy Clarity",
        "Dashboard Usefulness",
        "Report Usefulness",
        "Integration Gaps",
        "Procurement Concerns",
        "Go/No-Go Decision",
        "AISPM Trial Outcome Summary",
        "renderAispmTrialOutcomeSummary",
        "CSO/CISO Outcome",
        "Go candidate",
        "Journey Coverage",
        "AISPM Trial Review Packet Export",
        "buildAispmTrialReviewPacket",
        "copyAispmTrialReviewPacket",
        "downloadAispmTrialReviewPacket",
        "cavra.aispm.trial_review_packet.v1",
        "cavra-aispm-trial-review-packet.json",
        "AISPM Trial Review Packet Integrity",
        "renderAispmTrialReviewPacketIntegrity",
        "license_signing_key",
        "private_registry_credentials",
        "enterprise_source_code",
        "hosted_telemetry_events",
        "AISPM Trial Procurement Readiness",
        "renderAispmTrialProcurementReadiness",
        "Legal Review",
        "Security Review",
        "Deployment Review",
        "Support Review",
        "Licensing Review",
        "Data Handling",
        "Pilot Scope",
        "AISPM Trial Pilot Scope Builder",
        "renderAispmTrialPilotScope",
        "Target Repositories",
        "AI Agents",
        "Required Checks",
        "Evidence Owners",
        "Success Criteria",
        "Go/No-Go Date",
        "AISPM Trial Pilot Scope Packet",
        "copyAispmTrialPilotScopePacket",
        "downloadAispmTrialPilotScopePacket",
        "cavra.aispm.trial_pilot_scope_packet.v1",
        "cavra-aispm-trial-pilot-scope-packet.json",
        "AISPM Pilot Approval Checklist",
        "renderAispmPilotApprovalChecklist",
        "AISPM Pilot Approval Packet",
        "copyAispmPilotApprovalPacket",
        "downloadAispmPilotApprovalPacket",
        "cavra.aispm.pilot_approval_packet.v1",
        "cavra-aispm-pilot-approval-packet.json",
        "signed_approval_workflow",
        "workflow_write_back",
        "identity_bound_approvals",
        "Owner Assigned",
        "Repos Selected",
        "Agents Registered",
        "Checks Enforced",
        "Policies Selected",
        "Evidence Owners Assigned",
        "Support Path Confirmed",
        "Go/No-Go Date Accepted",
        "AISPM Pilot Launch Readiness Summary",
        "renderAispmPilotLaunchReadiness",
        "AISPM Pilot Launch Decision Packet",
        "copyAispmPilotLaunchDecisionPacket",
        "downloadAispmPilotLaunchDecisionPacket",
        "cavra.aispm.pilot_launch_decision_packet.v1",
        "cavra-aispm-pilot-launch-decision-packet.json",
        "signed_launch_approval",
        "identity_bound_decision_evidence",
        "approval_workflow_write_back",
        "tenant_live_readiness_state",
        "Scope Defined",
        "Approvals Prepared",
        "Reports Available",
        "Evidence Reviewed",
        "Support Confirmed",
        "Go/No-Go Ready",
        "Production Pilot Evidence Room",
        "renderAispmPilotEvidenceRoom",
        "Production Pilot Evidence Room Packet",
        "copyAispmPilotEvidenceRoomPacket",
        "downloadAispmPilotEvidenceRoomPacket",
        "cavra.aispm.pilot_evidence_room_packet.v1",
        "cavra-aispm-pilot-evidence-room-packet.json",
        "authenticated_evidence_room_access",
        "signed_reviewer_activity_logs",
        "evidence_retention_policy_enforcement",
        "tenant_artifact_permissions",
        "CSO/CISO",
        "Security",
        "Platform",
        "Procurement",
        "Auditor",
        "Operator",
        "authenticated evidence-room access",
        "signed activity logs",
        "Evidence Room Reviewer Checklist",
        "renderAispmEvidenceReviewerChecklist",
        "Evidence Room Reviewer Checklist Packet",
        "copyAispmEvidenceReviewerChecklistPacket",
        "downloadAispmEvidenceReviewerChecklistPacket",
        "cavra.aispm.evidence_reviewer_checklist_packet.v1",
        "cavra-aispm-evidence-reviewer-checklist-packet.json",
        "Go/no-go owner named",
        "Risk exceptions documented",
        "Pilot guardrails enforceable",
        "Commercial trial path understood",
        "Audit trail reviewable",
        "Operator runbook ready",
        "requires_enterprise_signed_decision",
        "requires_enterprise_operator_activity_log",
        "signed_reviewer_acceptance",
        "identity_bound_reviewer_records",
        "checklist_workflow_write_back",
        "tenant_exception_records",
        "Pilot Exception Register",
        "renderAispmPilotExceptionRegister",
        "Pilot Exception Register Packet",
        "copyAispmPilotExceptionRegisterPacket",
        "downloadAispmPilotExceptionRegisterPacket",
        "cavra.aispm.pilot_exception_register_packet.v1",
        "cavra-aispm-pilot-exception-register-packet.json",
        "Support ownership",
        "Signed launch decision",
        "Workflow write-back",
        "Tenant evidence retention",
        "Policy context depth",
        "Commercial trial record",
        "requires_enterprise_support_assignment",
        "signed_exception_acceptance",
        "exception_owner_assignment",
        "exception_expiry_enforcement",
        "exception_closure_workflow",
        "tenant_exception_history",
        "Pilot Risk Acceptance Summary",
        "renderAispmPilotRiskAcceptanceSummary",
        "Pilot Risk Acceptance Packet",
        "copyAispmPilotRiskAcceptancePacket",
        "downloadAispmPilotRiskAcceptancePacket",
        "cavra.aispm.pilot_risk_acceptance_packet.v1",
        "cavra-aispm-pilot-risk-acceptance-packet.json",
        "Open Exceptions",
        "Accepted Risks",
        "Monitored Risks",
        "Accountable Owners",
        "Launch Blocking",
        "signed risk acceptance remains Enterprise-only",
        "signed_risk_acceptance",
        "identity_bound_risk_owner_records",
        "risk_acceptance_workflow_write_back",
        "tenant_risk_acceptance_history",
        "Pilot Launch Board Pack",
        "renderAispmPilotLaunchBoardPack",
        "Pilot Launch Board Pack Packet",
        "copyAispmPilotLaunchBoardPackPacket",
        "downloadAispmPilotLaunchBoardPackPacket",
        "cavra.aispm.pilot_launch_board_pack_packet.v1",
        "cavra-aispm-pilot-launch-board-pack-packet.json",
        "Pilot Control Readiness",
        "renderAispmPilotControlReadiness",
        "Pilot Control Readiness Packet",
        "copyAispmPilotControlReadinessPacket",
        "downloadAispmPilotControlReadinessPacket",
        "cavra.aispm.pilot_control_readiness_packet.v1",
        "cavra-aispm-pilot-control-readiness-packet.json",
        "scripts/validate-aispm-pilot-control-readiness.py",
        "Release Evidence Index",
        "renderAispmReleaseEvidenceIndex",
        "copyAispmReleaseEvidenceIndexPacket",
        "downloadAispmReleaseEvidenceIndexPacket",
        "cavra.aispm.release_evidence_index_packet.v1",
        "cavra-aispm-release-evidence-index-packet.json",
        "scripts/validate-aispm-release-evidence-index.py",
        "Hosted Release Operator Status",
        "renderAispmHostedReleaseStatus",
        "copyAispmHostedReleaseStatusPacket",
        "downloadAispmHostedReleaseStatusPacket",
        "cavra.hosted_sandbox.operator_release_status_packet.v1",
        "cavra-hosted-sandbox-operator-status-packet.json",
        "scripts/validate-hosted-sandbox-operator-status.py",
        "cavra-hosted-sandbox-post-deploy-evidence",
        "artifact_manifest",
        "freshness_gate",
        "scripts/validate-aispm-launch-artifacts.py",
        "Launch Decision",
        "Evidence Room",
        "Risk Acceptance",
        "Reviewer Checklist",
        "Executive Reports",
        "signed board approval",
        "board_minutes_and_attestation",
        "pdf_generation_and_delivery",
        "recipient_allowlists_and_email_audit",
        "tenant_artifact_retention",
        "CAVRA_LICENSE_KEY required",
        "hello@mind-ops.cloud",
        "cavra.aispm.enterprise_trial_readiness_packet.v1",
        "cavra-aispm-enterprise-trial-readiness-packet.json",
        "Trial readiness export",
        "Lab Notebook",
        "Access Portal",
        "Operator Approval",
        "Revocation And Expiry",
        "Release Evidence",
        "Enterprise Automation",
        "CSO Report Center",
        "CSO Report Catalog Readiness",
        "Report Catalog Readiness Packet",
        "cavra-aispm-report-catalog-packet.json",
        "copyAispmReportCatalogPacket",
        "downloadAispmReportCatalogPacket",
        "scripts/validate-aispm-report-catalog-readiness.py",
        "Report Delivery Setup Readiness",
        "Report Delivery Setup Packet",
        "cavra-aispm-report-delivery-setup-packet.json",
        "copyAispmReportSetupPacket",
        "downloadAispmReportSetupPacket",
        "scripts/validate-aispm-report-delivery-setup-readiness.py",
        "Report Operations Readiness",
        "Report Operations Readiness Packet",
        "cavra-aispm-report-operations-readiness-packet.json",
        "copyAispmReportOperationsPacket",
        "downloadAispmReportOperationsPacket",
        "scripts/validate-aispm-report-operations-readiness.py",
        "Report Governance Readiness",
        "Report Governance Readiness Packet",
        "cavra-aispm-report-governance-readiness-packet.json",
        "copyAispmReportGovernancePacket",
        "downloadAispmReportGovernancePacket",
        "scripts/validate-aispm-report-governance-readiness.py",
        "Report Assurance Readiness",
        "Report Assurance Readiness Packet",
        "cavra-aispm-report-assurance-readiness-packet.json",
        "copyAispmReportAssurancePacket",
        "downloadAispmReportAssurancePacket",
        "scripts/validate-aispm-report-assurance-readiness.py",
        "Report Response Readiness",
        "Report Response Readiness Packet",
        "cavra-aispm-report-response-readiness-packet.json",
        "copyAispmReportResponsePacket",
        "downloadAispmReportResponsePacket",
        "scripts/validate-aispm-report-response-readiness.py",
        "Report Trial Operations Readiness",
        "Report Trial Operations Readiness Packet",
        "cavra-aispm-report-trial-operations-readiness-packet.json",
        "copyAispmReportTrialOpsPacket",
        "downloadAispmReportTrialOpsPacket",
        "scripts/validate-aispm-report-trial-operations-readiness.py",
        "Pilot Control Readiness",
        "Pilot Control Readiness Packet",
        "cavra-aispm-pilot-control-readiness-packet.json",
        "copyAispmPilotControlReadinessPacket",
        "downloadAispmPilotControlReadinessPacket",
        "scripts/validate-aispm-pilot-control-readiness.py",
        "Executive Risk Brief",
        "Board KPI Pack",
        "SOC 2-Style Audit Summary",
        "Control Coverage Export",
        "Evidence Freshness Export",
        "Agent Risk Register",
        "Scheduled Email Delivery",
        "cavra-aispm-executive-risk-brief.md",
        "cavra-aispm-board-kpi-pack.json",
        "cavra-aispm-soc2-audit-summary.md",
        "cavra-aispm-control-coverage.csv",
        "cavra-aispm-evidence-freshness.csv",
        "cavra-aispm-agent-risk-register.csv",
        "copyAispmReplayPolicyCiGateAuditPacket",
        "downloadAispmReplayPolicyCiGateAuditPacket",
        "CI Gate Readiness Export",
        "cavra-replay-policy-ci-gate-readiness.json",
        "cavra aispm validate-ci-gate-readiness cavra-replay-policy-ci-gate-readiness.json --repo-root .",
        "/aispm/replay-to-policy-ci-gate-readiness/validate",
        "copyAispmReplayPolicyCiGateReadiness",
        "downloadAispmReplayPolicyCiGateReadiness",
        "cavra.aispm.replay_to_policy_ci_gate_readiness.v1",
        "cavra-aispm-review-packet",
        "examples/github-actions/cavra-aispm-review-packet-validation.yml",
        "examples/gitlab-ci/cavra-aispm-review-packet-validation.gitlab-ci.yml",
        "examples/azure-pipelines/cavra-aispm-review-packet-validation.azure-pipelines.yml",
        "copyAispmReplayPolicyTests",
        "downloadAispmReplayPolicyTests",
        "copyTextToClipboard",
        "cavra-replay-policy-tests.json",
        "renderAispmTraceReplay",
        "loadAispmTraceReplay",
        "loadAispmDashboard",
        "/aispm/posture",
        "/aispm/replay-to-policy-draft",
        "/aispm/replay-to-policy-tests",
        "/aispm/approval-lineage",
        "/aispm/behavior-fingerprints",
        "/aispm/policy-context-gaps",
        "/aispm/pre-action-risk-forecasts",
        "/aispm/intent-action-drift",
        "/aispm/tool-chain-graph",
        "/aispm/agent-blast-radius",
        "/aispm/control-coverage-heatmap",
        "/aispm/evidence-confidence",
        "/aispm/evidence-freshness",
        "/aispm/executive-risk-narrative",
        "/aispm/trace-replay/",
        "approval_lineage",
        "behavior_fingerprints",
        "policy_context_gaps",
        "pre_action_risk_forecasts",
        "intent_action_drift",
        "tool_chain_graph",
        "agent_blast_radius",
        "control_coverage_heatmap",
        "evidence_confidence_drilldown",
        "evidence_freshness_slo",
        "executive_risk_narrative",
        "control_coverage",
        "near_misses",
        "trace_replay",
        "requires_cavra_enterprise",
    ]:
        require(js, needle, "architecture node contract", failures)

    for needle in [
        "renderCompliance",
        "NIST",
        "SOC2",
        "ISO27001",
        "CIS",
        "PCI DSS",
        "OWASP",
    ]:
        require_any([html, js], needle, "compliance filter contract", failures)

    workflow_needles = [
        "node --check apps/sandbox-ui/config.js",
        "node --check apps/sandbox-ui/sandbox.js",
        "python scripts/validate-sandbox-portal.py",
        "python scripts/validate-aispm-launch-artifacts.py",
        "npm run validate:sandbox:visual",
        "python scripts/validate-aispm-launch-readiness.py",
        "python scripts/validate-aispm-release-evidence-index.py",
        "python scripts/validate-aispm-report-operations-readiness.py",
        "python scripts/validate-aispm-report-governance-readiness.py",
        "python scripts/validate-aispm-report-assurance-readiness.py",
        "python scripts/validate-aispm-report-response-readiness.py",
        "python scripts/validate-aispm-report-trial-operations-readiness.py",
        "python scripts/validate-aispm-pilot-control-readiness.py",
        "npm run validate:sandbox:hosted",
        "scripts/validate-hosted-sandbox-pages.mjs",
        "python scripts/generate-hosted-sandbox-deploy-evidence.py",
        "python scripts/validate-hosted-sandbox-deploy-evidence.py",
        "actions/upload-artifact@v4",
        "cavra-hosted-sandbox-post-deploy-evidence",
        "CAVRA_PUBLIC_TRIAL_API_URL",
        'grep -q "Evidence Console"',
        'grep -q "Community GA Control Hardening"',
        'grep -q "Production Pilot Readiness"',
        'grep -q "Enterprise Trial Access Portal"',
        'grep -q "AISPM Trial Lab Notebook Readiness"',
        'grep -q "Report Operations Readiness"',
        'grep -q "Report Governance Readiness"',
        'grep -q "Report Assurance Readiness"',
        'grep -q "Report Response Readiness"',
        'grep -q "Report Trial Operations Readiness"',
        'grep -q "Pilot Control Readiness"',
        'grep -q "cavra-aispm-pilot-control-readiness-packet.json"',
        'grep -q "aispm-trial-lab-notebook-publication-readiness-summary.md"',
        'grep -q "https://cavra-trial.mind-ops.cloud/"',
        "sandbox.js",
        "styles.css",
        "brand/cavra-mark.svg",
        "assets/brand/cavra-logo-horizontal.svg",
        "c4-container.svg",
        "evidence/before-the-agent-acts/evidence.json",
        "evidence/final-closeout-trial/sample-evidence-package.json",
        "evidence/final-closeout-trial/pilot-intake-template.json",
    ]
    for needle in workflow_needles:
        require(deploy, needle, "GitHub Pages smoke workflow", failures)

    for needle in [
        "./brand/favicon.svg",
        "./brand/cavra-mark.svg",
        "class=\"hero-product-mark\"",
        "Evidence Console",
        "Community GA Control Hardening",
        "Production Pilot Readiness",
        "Enterprise Trial Access Portal",
        "AISPM Trial Lab Notebook Readiness",
        'id="aispmTrialLabNotebookReadiness"',
        'id="enterprise-trial-lab-notebook-readiness"',
        "Open Readiness Summary",
        "Open Summary JSON",
        "Open Lab Notebook",
        "aispm-trial-lab-notebook-publication-readiness-summary.md",
        "aispm-trial-lab-notebook-publication-readiness-summary.json",
        "AISPM-Enterprise-Trial-Lab-Notebook",
        "https://cavra-trial.mind-ops.cloud/",
        "Open CAVRA Trial Portal",
    ]:
        require(html, needle, "brand and page signal", failures)

    for needle in [
        "trialAccessCards",
        "renderTrialAccess",
        "AISPM Trial Lab Notebook Readiness",
        "Trial Lab Notebook Readiness Summary",
        "Trial Lab Notebook Readiness JSON",
        "Enterprise Trial Lab Notebook Wiki",
        "docs/release-verifications/aispm-trial-lab-notebook-publication-readiness-summary.md",
    ]:
        require(js, needle, "Enterprise Trial portal contract", failures)

    require(readme, "docs/sandbox-portal-redesign.md", "README portal redesign link", failures)
    require(
        readme,
        "docs/sandbox-portal-smoke-validation.md",
        "README portal smoke validation link",
        failures,
    )
    require(
        wiki_home,
        "CAVRA-Developer-Portal-Redesign.md",
        "wiki portal redesign link",
        failures,
    )
    require(
        wiki_home,
        "CAVRA-Developer-Portal-Smoke-Validation.md",
        "wiki portal smoke validation link",
        failures,
    )

    for doc in [redesign_doc, smoke_doc, wiki_smoke_doc]:
        require(
            doc,
            "Node 24 readiness",
            "GA path next recommendation",
            failures,
        )

    if failures:
        print("CAVRA sandbox portal smoke validation failed:")
        for failure in failures:
            print(f"- {failure}")
        return 1

    print("CAVRA sandbox portal smoke validation passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
